#!/usr/bin/env python3
"""
Inject Nafes questions directly — no API needed.
All questions are stored as JSON strings and loaded at runtime to avoid
Python string escape conflicts with LaTeX backslashes.
"""
import json, os

DATA_FILE = "data/nafes.json"

# ---------------------------------------------------------------------------
# All new questions stored as a raw JSON string (safe from backslash issues)
# ---------------------------------------------------------------------------
RAW_JSON = r"""
[
  {"id":"NAFES-3-101","track":"nafes","level":"Grade 3","topic":"Addition","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 999 + 1 \\)?","options":["\\( 999 \\)","\\( 1{,}000 \\)","\\( 1{,}001 \\)","\\( 990 \\)"],"hint":"Think about what happens to the ones, tens, and hundreds.","explanation":"\\( 999 + 1 = 1{,}000 \\)."},"ar":{"question":"ما ناتج \\( 999 + 1 \\)؟","options":["\\( 999 \\)","\\( 1{,}000 \\)","\\( 1{,}001 \\)","\\( 990 \\)"],"hint":"فكّر فيما يحدث للآحاد والعشرات والمئات.","explanation":"\\( 999 + 1 = 1{,}000 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-102","track":"nafes","level":"Grade 3","topic":"Multiplication","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 12 \\times 3 \\)?","options":["\\( 33 \\)","\\( 36 \\)","\\( 39 \\)","\\( 42 \\)"],"hint":"Use the distributive property: \\( 12 \\times 3 = (10+2) \\times 3 \\).","explanation":"\\( 10 \\times 3 = 30 \\), \\( 2 \\times 3 = 6 \\), total \\( = 36 \\)."},"ar":{"question":"ما ناتج \\( 12 \\times 3 \\)؟","options":["\\( 33 \\)","\\( 36 \\)","\\( 39 \\)","\\( 42 \\)"],"hint":"\\( 12 \\times 3 = (10+2) \\times 3 \\).","explanation":"\\( 10 \\times 3 = 30 \\)، \\( 2 \\times 3 = 6 \\)، المجموع \\( = 36 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-103","track":"nafes","level":"Grade 3","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"A triangle has how many sides?","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 5 \\)"],"hint":"Think of the prefix 'tri'.","explanation":"A triangle has \\( 3 \\) sides."},"ar":{"question":"كم ضلعاً للمثلث؟","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 5 \\)"],"hint":"فكّر في كلمة 'ثلاثي'.","explanation":"للمثلث \\( 3 \\) أضلاع."}},"correct_index":"1"},
  {"id":"NAFES-3-104","track":"nafes","level":"Grade 3","topic":"Place Value","type":"MCQ","difficulty":"easy","content":{"en":{"question":"In \\( 5{,}308 \\), which digit is in the hundreds place?","options":["\\( 5 \\)","\\( 3 \\)","\\( 0 \\)","\\( 8 \\)"],"hint":"Count from the right: ones, tens, hundreds, thousands.","explanation":"In \\( 5{,}308 \\), the hundreds digit is \\( 3 \\)."},"ar":{"question":"في العدد \\( 5{,}308 \\)، ما الرقم في خانة المئات؟","options":["\\( 5 \\)","\\( 3 \\)","\\( 0 \\)","\\( 8 \\)"],"hint":"عدّ من اليمين: آحاد، عشرات، مئات، آلاف.","explanation":"في \\( 5{,}308 \\)، رقم المئات هو \\( 3 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-105","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A car travels \\( 120 \\) km on \\( 10 \\) litres of fuel. How far can it travel on \\( 5 \\) litres?","options":["\\( 50 \\) km","\\( 60 \\) km","\\( 70 \\) km","\\( 80 \\) km"],"hint":"Find km per litre, then multiply by \\( 5 \\).","explanation":"\\( 120 \\div 10 = 12 \\) km per litre. \\( 12 \\times 5 = 60 \\) km."},"ar":{"question":"تقطع سيارة \\( 120 \\) كم بـ\\( 10 \\) لترات. كم تقطع بـ\\( 5 \\) لترات؟","options":["\\( 50 \\) كم","\\( 60 \\) كم","\\( 70 \\) كم","\\( 80 \\) كم"],"hint":"احسب كيلومتر لكل لتر ثم اضرب في \\( 5 \\).","explanation":"\\( 120 \\div 10 = 12 \\) كم/لتر. \\( 12 \\times 5 = 60 \\) كم."}},"correct_index":"1"},
  {"id":"NAFES-3-106","track":"nafes","level":"Grade 3","topic":"Subtraction","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 1{,}000 - 437 \\)?","options":["\\( 563 \\)","\\( 573 \\)","\\( 553 \\)","\\( 583 \\)"],"hint":"Borrow through the zeros.","explanation":"\\( 1{,}000 - 437 = 563 \\)."},"ar":{"question":"ما ناتج \\( 1{,}000 - 437 \\)؟","options":["\\( 563 \\)","\\( 573 \\)","\\( 553 \\)","\\( 583 \\)"],"hint":"استعر عبر الأصفار.","explanation":"\\( 1{,}000 - 437 = 563 \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-107","track":"nafes","level":"Grade 3","topic":"Data","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Students voted: Apple=12, Mango=18, Banana=10. How many more votes did Mango get than Apple?","options":["\\( 4 \\)","\\( 6 \\)","\\( 8 \\)","\\( 10 \\)"],"hint":"Subtract Apple votes from Mango votes.","explanation":"\\( 18 - 12 = 6 \\) more votes for Mango."},"ar":{"question":"صوّت الطلاب: تفاح=12، مانجو=18، موز=10. بكم صوت تفوّق المانجو على التفاح؟","options":["\\( 4 \\)","\\( 6 \\)","\\( 8 \\)","\\( 10 \\)"],"hint":"اطرح أصوات التفاح من المانجو.","explanation":"\\( 18 - 12 = 6 \\) أصوات."}},"correct_index":"1"},
  {"id":"NAFES-3-108","track":"nafes","level":"Grade 3","topic":"Estimation","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Round \\( 347 \\) to the nearest hundred.","options":["\\( 300 \\)","\\( 350 \\)","\\( 400 \\)","\\( 340 \\)"],"hint":"Look at the tens digit to decide.","explanation":"The tens digit is \\( 4 \\) (less than \\( 5 \\)), so round down to \\( 300 \\)."},"ar":{"question":"قرّب \\( 347 \\) إلى أقرب مئة.","options":["\\( 300 \\)","\\( 350 \\)","\\( 400 \\)","\\( 340 \\)"],"hint":"انظر إلى رقم العشرات.","explanation":"رقم العشرات \\( 4 \\) (أقل من \\( 5 \\))، فنقرّب للأسفل إلى \\( 300 \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-109","track":"nafes","level":"Grade 3","topic":"Fractions","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is \\( \\dfrac{1}{4} + \\dfrac{2}{4} \\)?","options":["\\( \\dfrac{3}{8} \\)","\\( \\dfrac{3}{4} \\)","\\( \\dfrac{2}{4} \\)","\\( 1 \\)"],"hint":"When denominators are the same, add numerators only.","explanation":"\\( \\dfrac{1}{4} + \\dfrac{2}{4} = \\dfrac{3}{4} \\)."},"ar":{"question":"ما ناتج \\( \\dfrac{1}{4} + \\dfrac{2}{4} \\)؟","options":["\\( \\dfrac{3}{8} \\)","\\( \\dfrac{3}{4} \\)","\\( \\dfrac{2}{4} \\)","\\( 1 \\)"],"hint":"عندما يكون المقامان متساويين، اجمع البسطين فقط.","explanation":"\\( \\dfrac{1}{4} + \\dfrac{2}{4} = \\dfrac{3}{4} \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-110","track":"nafes","level":"Grade 3","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"I am a 2-digit number, greater than \\( 50 \\), and a multiple of \\( 9 \\). What is the smallest I can be?","options":["\\( 54 \\)","\\( 63 \\)","\\( 72 \\)","\\( 81 \\)"],"hint":"List multiples of \\( 9 \\) greater than \\( 50 \\).","explanation":"Multiples of \\( 9 \\) greater than \\( 50 \\): \\( 54, 63, 72, \\ldots \\). Smallest is \\( 54 \\)."},"ar":{"question":"أنا عدد من رقمين، أكبر من \\( 50 \\)، ومن مضاعفات \\( 9 \\). ما أصغر قيمة لي؟","options":["\\( 54 \\)","\\( 63 \\)","\\( 72 \\)","\\( 81 \\)"],"hint":"اذكر مضاعفات \\( 9 \\) الأكبر من \\( 50 \\).","explanation":"أصغر مضاعف لـ\\( 9 \\) أكبر من \\( 50 \\) هو \\( 54 \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-111","track":"nafes","level":"Grade 3","topic":"Division","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A teacher has \\( 84 \\) crayons to share equally among \\( 4 \\) tables. How many crayons per table?","options":["\\( 18 \\)","\\( 21 \\)","\\( 24 \\)","\\( 28 \\)"],"hint":"Divide \\( 84 \\) by \\( 4 \\).","explanation":"\\( 84 \\div 4 = 21 \\) crayons per table."},"ar":{"question":"معلمة لديها \\( 84 \\) قلم تلوين تريد توزيعها على \\( 4 \\) طاولات. كم قلماً لكل طاولة؟","options":["\\( 18 \\)","\\( 21 \\)","\\( 24 \\)","\\( 28 \\)"],"hint":"اقسم \\( 84 \\) على \\( 4 \\).","explanation":"\\( 84 \\div 4 = 21 \\) قلماً لكل طاولة."}},"correct_index":"1"},
  {"id":"NAFES-3-112","track":"nafes","level":"Grade 3","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which shape has exactly \\( 4 \\) equal sides and \\( 4 \\) right angles?","options":["Rectangle","Square","Rhombus","Trapezoid"],"hint":"All four sides are equal AND all angles are \\( 90° \\).","explanation":"A square has \\( 4 \\) equal sides and \\( 4 \\) right angles."},"ar":{"question":"أي الأشكال له \\( 4 \\) أضلاع متساوية و\\( 4 \\) زوايا قائمة؟","options":["مستطيل","مربع","معيّن","شبه منحرف"],"hint":"أضلاعه الأربعة متساوية وزواياه الأربع قائمة.","explanation":"المربع له \\( 4 \\) أضلاع متساوية و\\( 4 \\) زوايا قائمة."}},"correct_index":"1"},
  {"id":"NAFES-3-113","track":"nafes","level":"Grade 3","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What comes next: Triangle, Square, Triangle, Square, Triangle, ...?","options":["Triangle","Square","Circle","Star"],"hint":"The pattern alternates between two shapes.","explanation":"The pattern alternates triangle-square, so the next is Square."},"ar":{"question":"ما الشكل التالي: مثلث، مربع، مثلث، مربع، مثلث، ...؟","options":["مثلث","مربع","دائرة","نجمة"],"hint":"النمط يتناوب بين شكلين.","explanation":"النمط يتناوب مثلث-مربع، فالتالي مربع."}},"correct_index":"1"},
  {"id":"NAFES-3-114","track":"nafes","level":"Grade 3","topic":"Measurement","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which unit would you use to measure the weight of a watermelon?","options":["Millimetres","Centimetres","Kilograms","Kilometres"],"hint":"Weight is measured in grams or kilograms.","explanation":"Kilograms is the appropriate unit for measuring the weight of a watermelon."},"ar":{"question":"ما الوحدة المناسبة لقياس وزن بطيخة؟","options":["ملليمتر","سنتيمتر","كيلوغرام","كيلومتر"],"hint":"الوزن يُقاس بالغرام أو الكيلوغرام.","explanation":"الكيلوغرام هو الوحدة المناسبة."}},"correct_index":"2"},
  {"id":"NAFES-3-115","track":"nafes","level":"Grade 3","topic":"Number Sense","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which of these is a multiple of \\( 5 \\)?","options":["\\( 23 \\)","\\( 37 \\)","\\( 45 \\)","\\( 52 \\)"],"hint":"Multiples of \\( 5 \\) end in \\( 0 \\) or \\( 5 \\).","explanation":"\\( 45 \\) ends in \\( 5 \\), so it is a multiple of \\( 5 \\)."},"ar":{"question":"أيّ من هذه الأعداد مضاعف للعدد \\( 5 \\)؟","options":["\\( 23 \\)","\\( 37 \\)","\\( 45 \\)","\\( 52 \\)"],"hint":"مضاعفات \\( 5 \\) تنتهي بـ \\( 0 \\) أو \\( 5 \\).","explanation":"\\( 45 \\) ينتهي بـ \\( 5 \\) فهو مضاعف لـ \\( 5 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-116","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Three shelves have 24, 17, and 19 books. If \\( 15 \\) books are removed from the total, how many remain?","options":["\\( 45 \\)","\\( 50 \\)","\\( 55 \\)","\\( 60 \\)"],"hint":"First find the total, then subtract \\( 15 \\).","explanation":"Total: \\( 24+17+19=60 \\). After removing: \\( 60-15=45 \\)."},"ar":{"question":"ثلاثة رفوف تحتوي 24، 17، و19 كتاباً. إذا أُزيل \\( 15 \\) كتاباً من الإجمالي، كم يتبقى؟","options":["\\( 45 \\)","\\( 50 \\)","\\( 55 \\)","\\( 60 \\)"],"hint":"احسب الإجمالي أولاً ثم اطرح \\( 15 \\).","explanation":"الإجمالي: \\( 24+17+19=60 \\). الباقي: \\( 60-15=45 \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-117","track":"nafes","level":"Grade 3","topic":"Comparison","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which sign makes this true? \\( 563 \\; ? \\; 536 \\)","options":["\\( < \\)","\\( > \\)","\\( = \\)","Cannot determine"],"hint":"Compare the tens digits since the hundreds are equal.","explanation":"Hundreds are equal. Tens: \\( 6 > 3 \\), so \\( 563 > 536 \\)."},"ar":{"question":"أي علامة تجعل العبارة صحيحة؟ \\( 563 \\; ? \\; 536 \\)","options":["\\( < \\)","\\( > \\)","\\( = \\)","لا يمكن تحديده"],"hint":"قارن خانة العشرات.","explanation":"المئات متساوية. العشرات: \\( 6 > 3 \\)، إذن \\( 563 > 536 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-118","track":"nafes","level":"Grade 3","topic":"Multiplication","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A chicken lays \\( 4 \\) eggs per day. How many eggs will it lay in \\( 3 \\) weeks?","options":["\\( 84 \\)","\\( 72 \\)","\\( 96 \\)","\\( 68 \\)"],"hint":"\\( 3 \\) weeks \\( = 21 \\) days.","explanation":"\\( 3 \\times 7 = 21 \\) days. \\( 21 \\times 4 = 84 \\) eggs."},"ar":{"question":"تضع دجاجة \\( 4 \\) بيضات يومياً. كم بيضة ستضع في \\( 3 \\) أسابيع؟","options":["\\( 84 \\)","\\( 72 \\)","\\( 96 \\)","\\( 68 \\)"],"hint":"\\( 3 \\) أسابيع \\( = 21 \\) يوماً.","explanation":"\\( 21 \\times 4 = 84 \\) بيضة."}},"correct_index":"0"},
  {"id":"NAFES-3-119","track":"nafes","level":"Grade 3","topic":"Number Sense","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 50 \\times 6 \\)?","options":["\\( 250 \\)","\\( 300 \\)","\\( 350 \\)","\\( 320 \\)"],"hint":"\\( 50 \\times 6 = 5 \\times 6 \\times 10 \\).","explanation":"\\( 5 \\times 6 = 30 \\), then \\( \\times 10 = 300 \\)."},"ar":{"question":"ما ناتج \\( 50 \\times 6 \\)؟","options":["\\( 250 \\)","\\( 300 \\)","\\( 350 \\)","\\( 320 \\)"],"hint":"\\( 50 \\times 6 = 5 \\times 6 \\times 10 \\).","explanation":"\\( 5 \\times 6 = 30 \\)، ثم \\( \\times 10 = 300 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-120","track":"nafes","level":"Grade 3","topic":"Area","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A garden is \\( 9 \\) m long and \\( 4 \\) m wide. What is its area?","options":["\\( 26 \\) m²","\\( 32 \\) m²","\\( 36 \\) m²","\\( 40 \\) m²"],"hint":"Area \\( = l \\times w \\).","explanation":"Area \\( = 9 \\times 4 = 36 \\) m²."},"ar":{"question":"حديقة طولها \\( 9 \\) م وعرضها \\( 4 \\) م. ما مساحتها؟","options":["\\( 26 \\) م²","\\( 32 \\) م²","\\( 36 \\) م²","\\( 40 \\) م²"],"hint":"المساحة \\( = l \\times w \\).","explanation":"المساحة \\( = 9 \\times 4 = 36 \\) م²."}},"correct_index":"2"},
  {"id":"NAFES-3-121","track":"nafes","level":"Grade 3","topic":"Fractions","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Which fraction is closest to \\( 1 \\)?","options":["\\( \\dfrac{1}{2} \\)","\\( \\dfrac{3}{4} \\)","\\( \\dfrac{7}{8} \\)","\\( \\dfrac{2}{3} \\)"],"hint":"The closer to \\( 1 \\), the smaller the gap between numerator and denominator.","explanation":"\\( \\dfrac{7}{8} = 0.875 \\) is closest to \\( 1 \\)."},"ar":{"question":"أيّ الكسور أقرب إلى \\( 1 \\)؟","options":["\\( \\dfrac{1}{2} \\)","\\( \\dfrac{3}{4} \\)","\\( \\dfrac{7}{8} \\)","\\( \\dfrac{2}{3} \\)"],"hint":"كلما كان الفرق بين البسط والمقام أصغر، كان الكسر أقرب إلى \\( 1 \\).","explanation":"\\( \\dfrac{7}{8} = 0.875 \\) هو الأقرب إلى \\( 1 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-122","track":"nafes","level":"Grade 3","topic":"Time","type":"MCQ","difficulty":"medium","content":{"en":{"question":"How many minutes are in \\( 2 \\) hours and \\( 15 \\) minutes?","options":["\\( 120 \\)","\\( 130 \\)","\\( 135 \\)","\\( 140 \\)"],"hint":"\\( 1 \\) hour \\( = 60 \\) minutes.","explanation":"\\( 2 \\times 60 + 15 = 135 \\) minutes."},"ar":{"question":"كم دقيقة في \\( 2 \\) ساعة و\\( 15 \\) دقيقة؟","options":["\\( 120 \\)","\\( 130 \\)","\\( 135 \\)","\\( 140 \\)"],"hint":"\\( 1 \\) ساعة \\( = 60 \\) دقيقة.","explanation":"\\( 2 \\times 60 + 15 = 135 \\) دقيقة."}},"correct_index":"2"},
  {"id":"NAFES-3-123","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A box has \\( 6 \\) rows of oranges, \\( 8 \\) per row. \\( 12 \\) oranges were taken. How many remain?","options":["\\( 32 \\)","\\( 36 \\)","\\( 40 \\)","\\( 48 \\)"],"hint":"Find the total first, then subtract.","explanation":"Total: \\( 6 \\times 8 = 48 \\). Remaining: \\( 48 - 12 = 36 \\)."},"ar":{"question":"صندوق يحتوي \\( 6 \\) صفوف من البرتقال، \\( 8 \\) في كل صف. أُخرج \\( 12 \\) برتقالة. كم تبقّى؟","options":["\\( 32 \\)","\\( 36 \\)","\\( 40 \\)","\\( 48 \\)"],"hint":"احسب الإجمالي أولاً ثم اطرح.","explanation":"الإجمالي: \\( 6 \\times 8 = 48 \\). الباقي: \\( 48 - 12 = 36 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-124","track":"nafes","level":"Grade 3","topic":"Estimation","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Round \\( 752 \\) to the nearest ten.","options":["\\( 700 \\)","\\( 750 \\)","\\( 760 \\)","\\( 800 \\)"],"hint":"Look at the ones digit.","explanation":"The ones digit is \\( 2 \\) (less than \\( 5 \\)), so round down: \\( 750 \\)."},"ar":{"question":"قرّب \\( 752 \\) إلى أقرب عشرة.","options":["\\( 700 \\)","\\( 750 \\)","\\( 760 \\)","\\( 800 \\)"],"hint":"انظر إلى رقم الآحاد.","explanation":"رقم الآحاد \\( 2 \\) (أقل من \\( 5 \\))، فنقرّب للأسفل: \\( 750 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-125","track":"nafes","level":"Grade 3","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Ali has \\( 5 \\) coins worth \\( 2 \\) riyals total (\\( 100 \\) halalas \\( = 1 \\) riyal). Coins are \\( 25 \\) or \\( 50 \\) halalas. How many \\( 50 \\)-halala coins does he have?","options":["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)"],"hint":"\\( 2 \\) riyals \\( = 200 \\) halalas. Let \\( x \\) = number of 50-halala coins.","explanation":"\\( 50x + 25(5-x) = 200 \\Rightarrow 25x = 75 \\Rightarrow x = 3 \\)."},"ar":{"question":"لدى علي \\( 5 \\) قطع نقدية مجموعها \\( 2 \\) ريال. كلها إما \\( 25 \\) هللة أو \\( 50 \\) هللة. كم قطعة من فئة \\( 50 \\) هللة؟","options":["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)"],"hint":"\\( 2 \\) ريال \\( = 200 \\) هللة. ليكن \\( x \\) عدد قطع الـ\\( 50 \\).","explanation":"\\( 50x + 25(5-x) = 200 \\Rightarrow 25x = 75 \\Rightarrow x = 3 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-126","track":"nafes","level":"Grade 3","topic":"Multiplication","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 9 \\times 9 \\)?","options":["\\( 72 \\)","\\( 81 \\)","\\( 89 \\)","\\( 90 \\)"],"hint":"\\( 9 \\times 9 \\) is one less than \\( 9 \\times 10 \\).","explanation":"\\( 9 \\times 9 = 81 \\)."},"ar":{"question":"ما ناتج \\( 9 \\times 9 \\)؟","options":["\\( 72 \\)","\\( 81 \\)","\\( 89 \\)","\\( 90 \\)"],"hint":"\\( 9 \\times 9 \\) أقل بواحدة من \\( 9 \\times 10 \\).","explanation":"\\( 9 \\times 9 = 81 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-127","track":"nafes","level":"Grade 3","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A shape has \\( 3 \\) sides and one angle of \\( 90° \\). What type of triangle is it?","options":["Equilateral","Isosceles","Right","Obtuse"],"hint":"A \\( 90° \\) angle is called a right angle.","explanation":"A triangle with one \\( 90° \\) angle is a right triangle."},"ar":{"question":"شكل له \\( 3 \\) أضلاع وزاوية واحدة قائمة \\( 90° \\). ما نوع هذا المثلث؟","options":["متساوي الأضلاع","متساوي الساقين","قائم الزاوية","منفرج الزاوية"],"hint":"الزاوية \\( 90° \\) تُسمى زاوية قائمة.","explanation":"مثلث بزاوية قائمة يُسمى مثلثاً قائم الزاوية."}},"correct_index":"2"},
  {"id":"NAFES-3-128","track":"nafes","level":"Grade 3","topic":"Number Sense","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which number is between \\( 699 \\) and \\( 701 \\)?","options":["\\( 698 \\)","\\( 700 \\)","\\( 702 \\)","\\( 710 \\)"],"hint":"Find the number that falls between the two given numbers.","explanation":"\\( 700 \\) is between \\( 699 \\) and \\( 701 \\)."},"ar":{"question":"أيّ الأعداد يقع بين \\( 699 \\) و\\( 701 \\)؟","options":["\\( 698 \\)","\\( 700 \\)","\\( 702 \\)","\\( 710 \\)"],"hint":"أوجد العدد الواقع بين العددين.","explanation":"\\( 700 \\) يقع بين \\( 699 \\) و\\( 701 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-129","track":"nafes","level":"Grade 3","topic":"Data","type":"MCQ","difficulty":"medium","content":{"en":{"question":"In a pictograph (each star = 5), Lina has 3 stars, Sami has 5 stars, Reem has 2 stars. How many real stars does Sami have?","options":["\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 35 \\)"],"hint":"Multiply the number of pictograph symbols by 5.","explanation":"Sami has 5 symbols: \\( 5 \\times 5 = 25 \\)."},"ar":{"question":"في مخطط نجمي (كل نجمة = 5)، لينا لديها 3 نجوم، سامي 5 نجوم، ريم 2 نجمة. كم نجمة حقيقية لدى سامي؟","options":["\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 35 \\)"],"hint":"اضرب عدد الرموز في 5.","explanation":"لدى سامي 5 رموز: \\( 5 \\times 5 = 25 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-130","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A shop sold \\( 35 \\) red shirts and \\( 48 \\) blue shirts at \\( 20 \\) riyals each. How much did the shop collect?","options":["\\( 1{,}460 \\) riyals","\\( 1{,}600 \\) riyals","\\( 1{,}660 \\) riyals","\\( 1{,}720 \\) riyals"],"hint":"Find total shirts, then multiply by \\( 20 \\).","explanation":"Total shirts: \\( 35+48=83 \\). Revenue: \\( 83 \\times 20 = 1{,}660 \\) riyals."},"ar":{"question":"باع متجر \\( 35 \\) قميصاً أحمر و\\( 48 \\) قميصاً أزرق بـ\\( 20 \\) ريالاً لكل قميص. كم جمع؟","options":["\\( 1{,}460 \\) ريالاً","\\( 1{,}600 \\) ريالاً","\\( 1{,}660 \\) ريالاً","\\( 1{,}720 \\) ريالاً"],"hint":"احسب عدد القمصان ثم اضرب في \\( 20 \\).","explanation":"الإجمالي: \\( 35+48=83 \\). الإيراد: \\( 83 \\times 20 = 1{,}660 \\) ريالاً."}},"correct_index":"2"},
  {"id":"NAFES-3-131","track":"nafes","level":"Grade 3","topic":"Addition","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 348 + 276 + 114 \\)?","options":["\\( 728 \\)","\\( 738 \\)","\\( 748 \\)","\\( 758 \\)"],"hint":"Add step by step.","explanation":"\\( 348+276=624 \\), \\( 624+114=738 \\)."},"ar":{"question":"ما ناتج \\( 348 + 276 + 114 \\)؟","options":["\\( 728 \\)","\\( 738 \\)","\\( 748 \\)","\\( 758 \\)"],"hint":"اجمع خطوةً بخطوة.","explanation":"\\( 348+276=624 \\)، \\( 624+114=738 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-132","track":"nafes","level":"Grade 3","topic":"Division","type":"MCQ","difficulty":"hard","content":{"en":{"question":"\\( 100 \\) sweets shared equally among \\( 8 \\) children. Each child gets \\underline{\\phantom{x}} sweets with \\underline{\\phantom{x}} left over.","options":["12 each, 2 left","12 each, 4 left","13 each, 4 left","11 each, 2 left"],"hint":"Divide and find the remainder.","explanation":"\\( 100 \\div 8 = 12 \\) remainder \\( 4 \\). Each child gets \\( 12 \\) with \\( 4 \\) left over."},"ar":{"question":"\\( 100 \\) حلوى توزّع بالتساوي على \\( 8 \\) أطفال. كم يحصل كل طفل وكم يتبقى؟","options":["12 لكل طفل، يتبقى 2","12 لكل طفل، يتبقى 4","13 لكل طفل، يتبقى 4","11 لكل طفل، يتبقى 2"],"hint":"اقسم وأوجد الباقي.","explanation":"\\( 100 \\div 8 = 12 \\) والباقي \\( 4 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-133","track":"nafes","level":"Grade 3","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A rectangle is split into two squares, each with side \\( 5 \\) cm. What is the perimeter of the entire rectangle?","options":["\\( 20 \\) cm","\\( 25 \\) cm","\\( 30 \\) cm","\\( 40 \\) cm"],"hint":"The rectangle has length \\( 10 \\) cm and width \\( 5 \\) cm.","explanation":"Length \\( = 2 \\times 5 = 10 \\) cm. Perimeter \\( = 2(10+5) = 30 \\) cm."},"ar":{"question":"مستطيل مقسّم إلى مربعين، ضلع كل منهما \\( 5 \\) سم. ما محيط المستطيل كاملاً؟","options":["\\( 20 \\) سم","\\( 25 \\) سم","\\( 30 \\) سم","\\( 40 \\) سم"],"hint":"طول المستطيل \\( 10 \\) سم وعرضه \\( 5 \\) سم.","explanation":"الطول \\( = 10 \\) سم. المحيط \\( = 2(10+5) = 30 \\) سم."}},"correct_index":"2"},
  {"id":"NAFES-3-134","track":"nafes","level":"Grade 3","topic":"Number Sense","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is the smallest 4-digit number?","options":["\\( 999 \\)","\\( 1{,}000 \\)","\\( 1{,}001 \\)","\\( 100 \\)"],"hint":"The smallest 4-digit number uses only the digits \\( 0 \\) and \\( 1 \\).","explanation":"The smallest 4-digit number is \\( 1{,}000 \\)."},"ar":{"question":"ما أصغر عدد مؤلف من \\( 4 \\) أرقام؟","options":["\\( 999 \\)","\\( 1{,}000 \\)","\\( 1{,}001 \\)","\\( 100 \\)"],"hint":"أصغر عدد من \\( 4 \\) أرقام يحتوي الرقمين \\( 0 \\) و\\( 1 \\) فقط.","explanation":"أصغر عدد مؤلف من \\( 4 \\) أرقام هو \\( 1{,}000 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-135","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Ahmed reads \\( 15 \\) pages/day on weekdays (5 days) and \\( 25 \\) pages/day on weekends (2 days). How many pages does he read in \\( 2 \\) weeks?","options":["\\( 200 \\)","\\( 250 \\)","\\( 300 \\)","\\( 350 \\)"],"hint":"Calculate weekly total then multiply by \\( 2 \\).","explanation":"Weekdays: \\( 5 \\times 15=75 \\). Weekend: \\( 2 \\times 25=50 \\). Weekly: \\( 125 \\). Two weeks: \\( 250 \\)."},"ar":{"question":"يقرأ أحمد \\( 15 \\) صفحة يومياً أيام الأسبوع (5 أيام) و\\( 25 \\) صفحة في عطلة نهاية الأسبوع (يومان). كم صفحة يقرأ في أسبوعين؟","options":["\\( 200 \\)","\\( 250 \\)","\\( 300 \\)","\\( 350 \\)"],"hint":"احسب إجمالي الأسبوع ثم اضرب في \\( 2 \\).","explanation":"أيام الأسبوع: \\( 75 \\). العطلة: \\( 50 \\). أسبوع: \\( 125 \\). أسبوعان: \\( 250 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-136","track":"nafes","level":"Grade 3","topic":"Multiplication","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A bag of marbles has \\( 8 \\) red and \\( 4 \\) blue marbles. If you buy \\( 5 \\) bags, how many marbles do you have in total?","options":["\\( 48 \\)","\\( 55 \\)","\\( 60 \\)","\\( 65 \\)"],"hint":"Find marbles per bag, then multiply by \\( 5 \\).","explanation":"Per bag: \\( 8+4=12 \\). Total: \\( 12 \\times 5=60 \\)."},"ar":{"question":"كيس رخام يحتوي \\( 8 \\) رخامة حمراء و\\( 4 \\) زرقاء. إذا اشتريت \\( 5 \\) أكياس، كم رخامة لديك؟","options":["\\( 48 \\)","\\( 55 \\)","\\( 60 \\)","\\( 65 \\)"],"hint":"احسب الرخام في كل كيس ثم اضرب في \\( 5 \\).","explanation":"لكل كيس: \\( 8+4=12 \\). الإجمالي: \\( 12 \\times 5=60 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-137","track":"nafes","level":"Grade 3","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is the name of a shape with 0 sides and 0 corners?","options":["Square","Triangle","Circle","Pentagon"],"hint":"Think of a perfectly round shape.","explanation":"A circle has no sides or corners."},"ar":{"question":"ما اسم الشكل الذي له \\( 0 \\) أضلاع و\\( 0 \\) زوايا؟","options":["مربع","مثلث","دائرة","خماسي"],"hint":"فكّر في شكل دائري تام.","explanation":"الدائرة ليس لها أضلاع أو زوايا."}},"correct_index":"2"},
  {"id":"NAFES-3-138","track":"nafes","level":"Grade 3","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is the \\( 10^{th} \\) term in the sequence: \\( 5, 10, 15, 20, \\ldots \\)?","options":["\\( 45 \\)","\\( 50 \\)","\\( 55 \\)","\\( 60 \\)"],"hint":"The pattern adds \\( 5 \\) each time. \\( n^{th} \\) term \\( = 5n \\).","explanation":"\\( 10^{th} \\) term \\( = 5 \\times 10 = 50 \\)."},"ar":{"question":"ما الحد العاشر في المتتالية: \\( 5, 10, 15, 20, \\ldots \\)؟","options":["\\( 45 \\)","\\( 50 \\)","\\( 55 \\)","\\( 60 \\)"],"hint":"النمط يضيف \\( 5 \\) في كل مرة. الحد \\( n \\) هو \\( 5n \\).","explanation":"الحد العاشر \\( = 5 \\times 10 = 50 \\)."}},"correct_index":"1"},
  {"id":"NAFES-3-139","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Nora had \\( 250 \\) riyals. She spent half on books and \\( 30 \\) riyals on stationery. How much does she have left?","options":["\\( 90 \\) riyals","\\( 95 \\) riyals","\\( 95 \\) riyals","\\( 100 \\) riyals"],"hint":"Half of \\( 250 = 125 \\). Then subtract \\( 30 \\).","explanation":"Spent on books: \\( 250 \\div 2 = 125 \\). Left: \\( 250 - 125 - 30 = 95 \\) riyals."},"ar":{"question":"أنفقت نورة نصف مبلغها البالغ \\( 250 \\) ريالاً على كتب و\\( 30 \\) ريالاً على قرطاسية. كم تبقى معها؟","options":["\\( 90 \\) ريالاً","\\( 95 \\) ريالاً","\\( 95 \\) ريالاً","\\( 100 \\) ريالاً"],"hint":"نصف \\( 250 = 125 \\). ثم اطرح \\( 30 \\).","explanation":"الكتب: \\( 125 \\). الباقي: \\( 250-125-30=95 \\) ريالاً."}},"correct_index":"1"},
  {"id":"NAFES-3-140","track":"nafes","level":"Grade 3","topic":"Number Sense","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which of these is a factor of \\( 24 \\)?","options":["\\( 7 \\)","\\( 5 \\)","\\( 8 \\)","\\( 11 \\)"],"hint":"A factor divides evenly into \\( 24 \\) with no remainder.","explanation":"\\( 24 \\div 8 = 3 \\), so \\( 8 \\) is a factor of \\( 24 \\)."},"ar":{"question":"أيّ من هذه الأعداد قاسم لـ\\( 24 \\)؟","options":["\\( 7 \\)","\\( 5 \\)","\\( 8 \\)","\\( 11 \\)"],"hint":"القاسم هو الذي يقسم \\( 24 \\) بدون باقٍ.","explanation":"\\( 24 \\div 8 = 3 \\)، إذن \\( 8 \\) قاسم لـ\\( 24 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-141","track":"nafes","level":"Grade 3","topic":"Fractions","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( \\dfrac{5}{6} - \\dfrac{1}{6} \\)?","options":["\\( \\dfrac{4}{6} \\)","\\( \\dfrac{5}{12} \\)","\\( \\dfrac{4}{12} \\)","\\( \\dfrac{6}{6} \\)"],"hint":"Same denominator: just subtract numerators.","explanation":"\\( \\dfrac{5}{6} - \\dfrac{1}{6} = \\dfrac{4}{6} = \\dfrac{2}{3} \\)."},"ar":{"question":"ما ناتج \\( \\dfrac{5}{6} - \\dfrac{1}{6} \\)؟","options":["\\( \\dfrac{4}{6} \\)","\\( \\dfrac{5}{12} \\)","\\( \\dfrac{4}{12} \\)","\\( \\dfrac{6}{6} \\)"],"hint":"المقام واحد: اطرح البسطين فقط.","explanation":"\\( \\dfrac{5}{6} - \\dfrac{1}{6} = \\dfrac{4}{6} \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-142","track":"nafes","level":"Grade 3","topic":"Measurement","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A bottle holds \\( 500 \\) mL. How many bottles fill a \\( 3 \\) litre container?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 8 \\)"],"hint":"\\( 1 \\) litre \\( = 1{,}000 \\) mL.","explanation":"\\( 3 \\) L \\( = 3{,}000 \\) mL. \\( 3{,}000 \\div 500 = 6 \\) bottles."},"ar":{"question":"زجاجة تسع \\( 500 \\) مل. كم زجاجة تملأ وعاء سعته \\( 3 \\) لترات؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 8 \\)"],"hint":"\\( 1 \\) لتر \\( = 1{,}000 \\) مل.","explanation":"\\( 3 \\) لتر \\( = 3{,}000 \\) مل. \\( 3{,}000 \\div 500 = 6 \\) زجاجات."}},"correct_index":"2"},
  {"id":"NAFES-3-143","track":"nafes","level":"Grade 3","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A number is divisible by both \\( 2 \\) and \\( 3 \\). Which of these could it be?","options":["\\( 14 \\)","\\( 21 \\)","\\( 30 \\)","\\( 25 \\)"],"hint":"A number divisible by both 2 and 3 is divisible by 6.","explanation":"\\( 30 \\div 6 = 5 \\). \\( 30 \\) is divisible by both \\( 2 \\) and \\( 3 \\)."},"ar":{"question":"عدد قابل للقسمة على \\( 2 \\) و\\( 3 \\) معاً. أيّ من هذه الأعداد يمكن أن يكون؟","options":["\\( 14 \\)","\\( 21 \\)","\\( 30 \\)","\\( 25 \\)"],"hint":"العدد القابل للقسمة على 2 و3 معاً قابل للقسمة على 6.","explanation":"\\( 30 \\div 6 = 5 \\). \\( 30 \\) قابل للقسمة على \\( 2 \\) و\\( 3 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-144","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A school has \\( 12 \\) classrooms. Each room has \\( 30 \\) students. How many students are in the school?","options":["\\( 320 \\)","\\( 350 \\)","\\( 360 \\)","\\( 380 \\)"],"hint":"Multiply rooms by students per room.","explanation":"\\( 12 \\times 30 = 360 \\) students."},"ar":{"question":"مدرسة فيها \\( 12 \\) فصلاً. في كل فصل \\( 30 \\) طالباً. كم عدد الطلاب في المدرسة؟","options":["\\( 320 \\)","\\( 350 \\)","\\( 360 \\)","\\( 380 \\)"],"hint":"اضرب عدد الفصول في عدد الطلاب لكل فصل.","explanation":"\\( 12 \\times 30 = 360 \\) طالباً."}},"correct_index":"2"},
  {"id":"NAFES-3-145","track":"nafes","level":"Grade 3","topic":"Subtraction","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 5{,}000 - 3{,}248 \\)?","options":["\\( 1{,}752 \\)","\\( 1{,}762 \\)","\\( 1{,}742 \\)","\\( 1{,}852 \\)"],"hint":"Borrow carefully through the zeros.","explanation":"\\( 5{,}000 - 3{,}248 = 1{,}752 \\)."},"ar":{"question":"ما ناتج \\( 5{,}000 - 3{,}248 \\)؟","options":["\\( 1{,}752 \\)","\\( 1{,}762 \\)","\\( 1{,}742 \\)","\\( 1{,}852 \\)"],"hint":"استعر بعناية عبر الأصفار.","explanation":"\\( 5{,}000 - 3{,}248 = 1{,}752 \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-146","track":"nafes","level":"Grade 3","topic":"Number Sense","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 3{,}000 + 400 + 70 + 9 \\) written in standard form?","options":["\\( 3{,}479 \\)","\\( 3{,}749 \\)","\\( 3{,}497 \\)","\\( 3{,}974 \\)"],"hint":"Combine the thousands, hundreds, tens, and ones.","explanation":"\\( 3{,}000+400+70+9 = 3{,}479 \\)."},"ar":{"question":"ما الشكل الاعتيادي لـ\\( 3{,}000 + 400 + 70 + 9 \\)؟","options":["\\( 3{,}479 \\)","\\( 3{,}749 \\)","\\( 3{,}497 \\)","\\( 3{,}974 \\)"],"hint":"ادمج الآلاف والمئات والعشرات والآحاد.","explanation":"\\( 3{,}000+400+70+9 = 3{,}479 \\)."}},"correct_index":"0"},
  {"id":"NAFES-3-147","track":"nafes","level":"Grade 3","topic":"Division","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 90 \\div 6 \\)?","options":["\\( 12 \\)","\\( 14 \\)","\\( 15 \\)","\\( 16 \\)"],"hint":"Think: what times \\( 6 \\) equals \\( 90 \\)?","explanation":"\\( 6 \\times 15 = 90 \\), so \\( 90 \\div 6 = 15 \\)."},"ar":{"question":"ما ناتج \\( 90 \\div 6 \\)؟","options":["\\( 12 \\)","\\( 14 \\)","\\( 15 \\)","\\( 16 \\)"],"hint":"فكّر: ماذا يُضرب في \\( 6 \\) يساوي \\( 90 \\)؟","explanation":"\\( 6 \\times 15 = 90 \\)، إذن \\( 90 \\div 6 = 15 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-148","track":"nafes","level":"Grade 3","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"The perimeter of a square is \\( 40 \\) cm. What is its side length?","options":["\\( 8 \\) cm","\\( 10 \\) cm","\\( 12 \\) cm","\\( 5 \\) cm"],"hint":"Perimeter of a square \\( = 4 \\times s \\).","explanation":"\\( 4 \\times s = 40 \\), so \\( s = 10 \\) cm."},"ar":{"question":"محيط مربع يساوي \\( 40 \\) سم. ما طول ضلعه؟","options":["\\( 8 \\) سم","\\( 10 \\) سم","\\( 12 \\) سم","\\( 5 \\) سم"],"hint":"محيط المربع \\( = 4 \\times s \\).","explanation":"\\( 4 \\times s = 40 \\)، إذن \\( s = 10 \\) سم."}},"correct_index":"1"},
  {"id":"NAFES-3-149","track":"nafes","level":"Grade 3","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Fill in the blank: \\( 100, 91, 82, 73, \\_, 55 \\).","options":["\\( 60 \\)","\\( 62 \\)","\\( 64 \\)","\\( 66 \\)"],"hint":"Find the common difference in the pattern.","explanation":"The pattern decreases by \\( 9 \\) each time: \\( 73 - 9 = 64 \\)."},"ar":{"question":"أكمل: \\( 100, 91, 82, 73, \\_, 55 \\).","options":["\\( 60 \\)","\\( 62 \\)","\\( 64 \\)","\\( 66 \\)"],"hint":"أوجد الفرق المشترك في النمط.","explanation":"النمط ينقص \\( 9 \\) في كل مرة: \\( 73 - 9 = 64 \\)."}},"correct_index":"2"},
  {"id":"NAFES-3-150","track":"nafes","level":"Grade 3","topic":"Word Problems","type":"MCQ","difficulty":"hard","content":{"en":{"question":"There are \\( 4 \\) teams. Each team has \\( 11 \\) players. If \\( 8 \\) players are absent today, how many players are present?","options":["\\( 34 \\)","\\( 36 \\)","\\( 36 \\)","\\( 44 \\)"],"hint":"Find total players first, then subtract absent ones.","explanation":"Total: \\( 4 \\times 11 = 44 \\). Present: \\( 44 - 8 = 36 \\)."},"ar":{"question":"هناك \\( 4 \\) فرق، في كل فريق \\( 11 \\) لاعباً. إذا كان \\( 8 \\) لاعبين غائبين اليوم، كم لاعباً حاضراً؟","options":["\\( 34 \\)","\\( 36 \\)","\\( 36 \\)","\\( 44 \\)"],"hint":"احسب الإجمالي أولاً ثم اطرح الغائبين.","explanation":"الإجمالي: \\( 4 \\times 11 = 44 \\). الحاضرون: \\( 44 - 8 = 36 \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-090","track":"nafes","level":"Grade 6","topic":"Percentages","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A shirt costs \\( 120 \\) riyals. A \\( 25\\% \\) discount is applied. What is the sale price?","options":["\\( 85 \\) riyals","\\( 90 \\) riyals","\\( 95 \\) riyals","\\( 100 \\) riyals"],"hint":"Find \\( 25\\% \\) of \\( 120 \\) and subtract.","explanation":"\\( 25\\% \\times 120 = 30 \\). Sale price \\( = 120 - 30 = 90 \\) riyals."},"ar":{"question":"قميص سعره \\( 120 \\) ريالاً وعليه خصم \\( 25\\% \\). ما سعر البيع؟","options":["\\( 85 \\) ريالاً","\\( 90 \\) ريالاً","\\( 95 \\) ريالاً","\\( 100 \\) ريالاً"],"hint":"احسب \\( 25\\% \\) من \\( 120 \\) ثم اطرحها.","explanation":"\\( 25\\% \\times 120 = 30 \\). سعر البيع \\( = 120 - 30 = 90 \\) ريالاً."}},"correct_index":"1"},
  {"id":"NAFES-6-091","track":"nafes","level":"Grade 6","topic":"Algebra","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Solve for \\( x \\): \\( 3x + 7 = 22 \\).","options":["\\( x=4 \\)","\\( x=5 \\)","\\( x=6 \\)","\\( x=3 \\)"],"hint":"Subtract \\( 7 \\) from both sides, then divide by \\( 3 \\).","explanation":"\\( 3x = 15 \\). \\( x = 5 \\)."},"ar":{"question":"حلّ المعادلة: \\( 3x + 7 = 22 \\).","options":["\\( x=4 \\)","\\( x=5 \\)","\\( x=6 \\)","\\( x=3 \\)"],"hint":"اطرح \\( 7 \\) من الطرفين ثم اقسم على \\( 3 \\).","explanation":"\\( 3x = 15 \\). \\( x = 5 \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-092","track":"nafes","level":"Grade 6","topic":"Fractions","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( \\dfrac{3}{4} \\times \\dfrac{8}{9} \\)?","options":["\\( \\dfrac{24}{36} \\)","\\( \\dfrac{2}{3} \\)","\\( \\dfrac{11}{13} \\)","\\( \\dfrac{1}{3} \\)"],"hint":"Multiply numerators and denominators, then simplify.","explanation":"\\( \\dfrac{3 \\times 8}{4 \\times 9} = \\dfrac{24}{36} = \\dfrac{2}{3} \\)."},"ar":{"question":"ما ناتج \\( \\dfrac{3}{4} \\times \\dfrac{8}{9} \\)؟","options":["\\( \\dfrac{24}{36} \\)","\\( \\dfrac{2}{3} \\)","\\( \\dfrac{11}{13} \\)","\\( \\dfrac{1}{3} \\)"],"hint":"اضرب البسطين والمقامين ثم بسّط.","explanation":"\\( \\dfrac{24}{36} = \\dfrac{2}{3} \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-093","track":"nafes","level":"Grade 6","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the area of a triangle with base \\( 10 \\) cm and height \\( 8 \\) cm?","options":["\\( 40 \\) cm²","\\( 80 \\) cm²","\\( 20 \\) cm²","\\( 60 \\) cm²"],"hint":"Area \\( = \\dfrac{1}{2} \\times b \\times h \\).","explanation":"Area \\( = \\dfrac{1}{2} \\times 10 \\times 8 = 40 \\) cm²."},"ar":{"question":"ما مساحة مثلث قاعدته \\( 10 \\) سم وارتفاعه \\( 8 \\) سم؟","options":["\\( 40 \\) سم²","\\( 80 \\) سم²","\\( 20 \\) سم²","\\( 60 \\) سم²"],"hint":"المساحة \\( = \\dfrac{1}{2} \\times q \\times h \\).","explanation":"المساحة \\( = \\dfrac{1}{2} \\times 10 \\times 8 = 40 \\) سم²."}},"correct_index":"0"},
  {"id":"NAFES-6-094","track":"nafes","level":"Grade 6","topic":"Ratio","type":"MCQ","difficulty":"medium","content":{"en":{"question":"The ratio of boys to girls is \\( 3:5 \\). If there are \\( 24 \\) boys, how many girls are there?","options":["\\( 32 \\)","\\( 36 \\)","\\( 40 \\)","\\( 45 \\)"],"hint":"Set up the proportion.","explanation":"\\( g = \\dfrac{5 \\times 24}{3} = 40 \\) girls."},"ar":{"question":"نسبة البنين إلى البنات \\( 3:5 \\). إذا كان عدد البنين \\( 24 \\)، فكم عدد البنات؟","options":["\\( 32 \\)","\\( 36 \\)","\\( 40 \\)","\\( 45 \\)"],"hint":"ضع النسبة وحلّها.","explanation":"\\( g = \\dfrac{5 \\times 24}{3} = 40 \\) بنتاً."}},"correct_index":"2"},
  {"id":"NAFES-6-095","track":"nafes","level":"Grade 6","topic":"Decimals","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 3.6 \\times 2.5 \\)?","options":["\\( 8.5 \\)","\\( 9.0 \\)","\\( 9.5 \\)","\\( 10.0 \\)"],"hint":"Multiply as whole numbers then place the decimal.","explanation":"\\( 36 \\times 25 = 900 \\). Two decimal places: \\( 9.00 \\)."},"ar":{"question":"ما ناتج \\( 3.6 \\times 2.5 \\)؟","options":["\\( 8.5 \\)","\\( 9.0 \\)","\\( 9.5 \\)","\\( 10.0 \\)"],"hint":"اضرب كأعداد صحيحة ثم ضع الفاصلة.","explanation":"\\( 36 \\times 25 = 900 \\). منزلتان: \\( 9.00 \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-096","track":"nafes","level":"Grade 6","topic":"Integers","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( -8 + 13 - 5 \\)?","options":["\\( -1 \\)","\\( 0 \\)","\\( 1 \\)","\\( 2 \\)"],"hint":"Work left to right.","explanation":"\\( -8+13=5 \\). \\( 5-5=0 \\)."},"ar":{"question":"ما ناتج \\( -8 + 13 - 5 \\)؟","options":["\\( -1 \\)","\\( 0 \\)","\\( 1 \\)","\\( 2 \\)"],"hint":"اعمل من اليسار إلى اليمين.","explanation":"\\( -8+13=5 \\). \\( 5-5=0 \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-097","track":"nafes","level":"Grade 6","topic":"LCM and HCF","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is the LCM of \\( 12 \\) and \\( 18 \\)?","options":["\\( 24 \\)","\\( 36 \\)","\\( 48 \\)","\\( 6 \\)"],"hint":"List multiples of each and find the smallest common one.","explanation":"LCM of \\( 12 \\) and \\( 18 \\) is \\( 36 \\)."},"ar":{"question":"ما المضاعف المشترك الأصغر لـ\\( 12 \\) و\\( 18 \\)؟","options":["\\( 24 \\)","\\( 36 \\)","\\( 48 \\)","\\( 6 \\)"],"hint":"اذكر مضاعفات كل عدد وأوجد أصغرها مشتركاً.","explanation":"المضاعف المشترك الأصغر هو \\( 36 \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-098","track":"nafes","level":"Grade 6","topic":"Algebra","type":"MCQ","difficulty":"hard","content":{"en":{"question":"If \\( 2(x+3) = 14 \\), what is \\( x \\)?","options":["\\( 3 \\)","\\( 4 \\)","\\( 5 \\)","\\( 6 \\)"],"hint":"Divide both sides by \\( 2 \\) first.","explanation":"\\( x+3=7 \\). \\( x=4 \\)."},"ar":{"question":"إذا كان \\( 2(x+3) = 14 \\)، فما \\( x \\)؟","options":["\\( 3 \\)","\\( 4 \\)","\\( 5 \\)","\\( 6 \\)"],"hint":"اقسم الطرفين على \\( 2 \\) أولاً.","explanation":"\\( x+3=7 \\). \\( x=4 \\)."}},"correct_index":"1"},
  {"id":"NAFES-6-099","track":"nafes","level":"Grade 6","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A right triangle has legs \\( 6 \\) cm and \\( 8 \\) cm. What is the hypotenuse?","options":["\\( 9 \\) cm","\\( 10 \\) cm","\\( 11 \\) cm","\\( 12 \\) cm"],"hint":"Use the Pythagorean theorem: \\( a^2+b^2=c^2 \\).","explanation":"\\( 6^2+8^2=36+64=100=10^2 \\). Hypotenuse \\( =10 \\) cm."},"ar":{"question":"مثلث قائم ساقاه \\( 6 \\) سم و\\( 8 \\) سم. ما طول وتره؟","options":["\\( 9 \\) سم","\\( 10 \\) سم","\\( 11 \\) سم","\\( 12 \\) سم"],"hint":"استخدم مبرهنة فيثاغورس.","explanation":"\\( 6^2+8^2=100=10^2 \\). الوتر \\( =10 \\) سم."}},"correct_index":"1"},
  {"id":"NAFES-6-100","track":"nafes","level":"Grade 6","topic":"Statistics","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Find the mean of: \\( 70, 85, 90, 75, 80 \\).","options":["\\( 78 \\)","\\( 80 \\)","\\( 82 \\)","\\( 85 \\)"],"hint":"Sum all, then divide by count.","explanation":"Sum \\( =400 \\). Mean \\( =400 \\div 5=80 \\)."},"ar":{"question":"أوجد متوسط: \\( 70, 85, 90, 75, 80 \\).","options":["\\( 78 \\)","\\( 80 \\)","\\( 82 \\)","\\( 85 \\)"],"hint":"اجمع الكل ثم اقسم على العدد.","explanation":"المجموع \\( =400 \\). المتوسط \\( =400 \\div 5=80 \\)."}},"correct_index":"1"},
  {"id":"NAFES-9-100","track":"nafes","level":"Grade 9","topic":"Algebra","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Solve: \\( 2x^2 - 8 = 0 \\).","options":["\\( x = \\pm 2 \\)","\\( x = \\pm 4 \\)","\\( x = 2 \\) only","\\( x = 4 \\) only"],"hint":"Divide by \\( 2 \\), then take the square root.","explanation":"\\( x^2=4 \\). \\( x= \\pm 2 \\)."},"ar":{"question":"حلّ: \\( 2x^2 - 8 = 0 \\).","options":["\\( x = \\pm 2 \\)","\\( x = \\pm 4 \\)","\\( x = 2 \\) فقط","\\( x = 4 \\) فقط"],"hint":"اقسم على \\( 2 \\) ثم استخرج الجذر.","explanation":"\\( x^2=4 \\). \\( x= \\pm 2 \\)."}},"correct_index":"0"},
  {"id":"NAFES-9-101","track":"nafes","level":"Grade 9","topic":"Coordinate Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the slope of the line through \\( (2,3) \\) and \\( (6,11) \\)?","options":["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)"],"hint":"Slope \\( = \\dfrac{y_2-y_1}{x_2-x_1} \\).","explanation":"\\( m = \\dfrac{11-3}{6-2} = \\dfrac{8}{4} = 2 \\)."},"ar":{"question":"ما ميل الخط المار بـ\\( (2,3) \\) و\\( (6,11) \\)؟","options":["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)"],"hint":"الميل \\( = \\dfrac{y_2-y_1}{x_2-x_1} \\).","explanation":"\\( m = \\dfrac{8}{4} = 2 \\)."}},"correct_index":"1"},
  {"id":"NAFES-9-102","track":"nafes","level":"Grade 9","topic":"Probability","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A bag has \\( 4 \\) red and \\( 6 \\) blue balls. What is the probability of picking a red ball?","options":["\\( \\dfrac{2}{5} \\)","\\( \\dfrac{3}{5} \\)","\\( \\dfrac{4}{9} \\)","\\( \\dfrac{1}{4} \\)"],"hint":"P \\( = \\dfrac{\\text{favourable}}{\\text{total}} \\).","explanation":"P(red) \\( = \\dfrac{4}{10} = \\dfrac{2}{5} \\)."},"ar":{"question":"حقيبة تحتوي \\( 4 \\) كرات حمراء و\\( 6 \\) زرقاء. ما احتمال سحب كرة حمراء؟","options":["\\( \\dfrac{2}{5} \\)","\\( \\dfrac{3}{5} \\)","\\( \\dfrac{4}{9} \\)","\\( \\dfrac{1}{4} \\)"],"hint":"الاحتمال \\( = \\dfrac{\\text{المرغوبة}}{\\text{الكلية}} \\).","explanation":"\\( \\dfrac{4}{10} = \\dfrac{2}{5} \\)."}},"correct_index":"0"},
  {"id":"NAFES-9-103","track":"nafes","level":"Grade 9","topic":"Systems of Equations","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Solve: \\( x+y=10 \\) and \\( x-y=4 \\).","options":["\\( x=6, y=4 \\)","\\( x=7, y=3 \\)","\\( x=8, y=2 \\)","\\( x=5, y=5 \\)"],"hint":"Add the two equations to eliminate \\( y \\).","explanation":"\\( 2x=14 \\Rightarrow x=7 \\). \\( y=3 \\)."},"ar":{"question":"حلّ: \\( x+y=10 \\) و\\( x-y=4 \\).","options":["\\( x=6, y=4 \\)","\\( x=7, y=3 \\)","\\( x=8, y=2 \\)","\\( x=5, y=5 \\)"],"hint":"اجمع المعادلتين.","explanation":"\\( 2x=14 \\Rightarrow x=7 \\). \\( y=3 \\)."}},"correct_index":"1"},
  {"id":"NAFES-9-104","track":"nafes","level":"Grade 9","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Angles of a quadrilateral are \\( 80°, 100°, 90°, x° \\). Find \\( x \\).","options":["\\( 80° \\)","\\( 85° \\)","\\( 90° \\)","\\( 95° \\)"],"hint":"Sum of angles in a quadrilateral \\( = 360° \\).","explanation":"\\( 80+100+90+x=360 \\Rightarrow x=90° \\)."},"ar":{"question":"زوايا رباعي: \\( 80°, 100°, 90°, x° \\). أوجد \\( x \\).","options":["\\( 80° \\)","\\( 85° \\)","\\( 90° \\)","\\( 95° \\)"],"hint":"مجموع زوايا الرباعي \\( = 360° \\).","explanation":"\\( x=90° \\)."}},"correct_index":"2"},
  {"id":"NAFES-9-105","track":"nafes","level":"Grade 9","topic":"Statistics","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Scores of 5 students: \\( 70, 90, 85, 65, 90 \\). What is the median?","options":["\\( 85 \\)","\\( 80 \\)","\\( 90 \\)","\\( 70 \\)"],"hint":"Order the scores and find the middle value.","explanation":"Ordered: \\( 65,70,85,90,90 \\). Median \\( =85 \\)."},"ar":{"question":"درجات 5 طلاب: \\( 70,90,85,65,90 \\). ما الوسيط؟","options":["\\( 85 \\)","\\( 80 \\)","\\( 90 \\)","\\( 70 \\)"],"hint":"رتّب الدرجات وأوجد القيمة الوسطى.","explanation":"مرتبة: \\( 65,70,85,90,90 \\). الوسيط \\( =85 \\)."}},"correct_index":"0"}
]
"""

new_questions = json.loads(RAW_JSON)

with open(DATA_FILE, "r", encoding="utf-8") as f:
    all_questions = json.load(f)

existing_ids = {q["id"] for q in all_questions}
to_add = [q for q in new_questions if q["id"] not in existing_ids]
all_questions.extend(to_add)

with open(DATA_FILE, "w", encoding="utf-8") as f:
    json.dump(all_questions, f, ensure_ascii=False, indent=2)

g3 = sum(1 for q in all_questions if q.get("level") == "Grade 3")
g6 = sum(1 for q in all_questions if q.get("level") == "Grade 6")
g9 = sum(1 for q in all_questions if q.get("level") == "Grade 9")
print(f"Added {len(to_add)} questions.")
print(f"Grade 3: {g3}/250 | Grade 6: {g6}/250 | Grade 9: {g9}/250 | Total: {len(all_questions)}")
