#!/usr/bin/env python3
"""Kangaroo Ecolier batch 2: questions 81-160"""
import json
DATA_FILE = "data/kangaroo.json"
RAW = r"""
[
  {"id":"KANG-ECO-081","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 11 \\times 11 \\)?","options":["\\(111\\)","\\(121\\)","\\(131\\)","\\(141\\)"],"hint":"11 elevens.","explanation":"\\(121\\)."},"ar":{"question":"ما ناتج \\( 11 \\times 11 \\)؟","options":["\\(111\\)","\\(121\\)","\\(131\\)","\\(141\\)"],"hint":"أحد عشر مرات أحد عشر.","explanation":"\\(121\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-082","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which month comes after March?","options":["February","April","May","June"],"hint":"January, February, March, April...","explanation":"April."},"ar":{"question":"أيّ شهر يأتي بعد مارس؟","options":["فبراير","أبريل","مايو","يونيو"],"hint":"يناير، فبراير، مارس، أبريل...","explanation":"أبريل."}},"correct_index":"1"},
  {"id":"KANG-ECO-083","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"\\(48 \\div 6 = \\)?","options":["\\(6\\)","\\(7\\)","\\(8\\)","\\(9\\)"],"hint":"6 × ? = 48.","explanation":"\\(8\\)."},"ar":{"question":"\\(48 \\div 6 = \\)؟","options":["\\(6\\)","\\(7\\)","\\(8\\)","\\(9\\)"],"hint":"6 × ؟ = 48.","explanation":"\\(8\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-084","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"An equilateral triangle has all three sides equal to 5 cm. What is its perimeter?","options":["\\(10\\)","\\(12\\)","\\(15\\)","\\(20\\)"],"hint":"3 × 5.","explanation":"\\(15\\) cm."},"ar":{"question":"مثلث متساوي الأضلاع كل ضلع فيه 5 سم. ما محيطه؟","options":["\\(10\\)","\\(12\\)","\\(15\\)","\\(20\\)"],"hint":"3 × 5.","explanation":"\\(15\\) سم."}},"correct_index":"2"},
  {"id":"KANG-ECO-085","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Noor has 20 SAR. She buys a pen for 7 SAR. How much is left?","options":["\\(11\\)","\\(12\\)","\\(13\\)","\\(14\\)"],"hint":"20 - 7.","explanation":"\\(13\\)."},"ar":{"question":"نور معها 20 ريال. اشترت قلم بـ7 ريال. كم بقي؟","options":["\\(11\\)","\\(12\\)","\\(13\\)","\\(14\\)"],"hint":"20 - 7.","explanation":"\\(13\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-086","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"easy","content":{"en":{"question":"10, 20, 30, __, 50. What is the missing number?","options":["\\(35\\)","\\(40\\)","\\(45\\)","\\(42\\)"],"hint":"Multiples of 10.","explanation":"\\(40\\)."},"ar":{"question":"10, 20, 30, __, 50. ما العدد المفقود؟","options":["\\(35\\)","\\(40\\)","\\(45\\)","\\(42\\)"],"hint":"مضاعفات 10.","explanation":"\\(40\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-087","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 5 + 5 + 5 + 5 + 5 \\)?","options":["\\(20\\)","\\(25\\)","\\(30\\)","\\(35\\)"],"hint":"5 × 5.","explanation":"\\(25\\)."},"ar":{"question":"ما ناتج \\( 5 + 5 + 5 + 5 + 5 \\)؟","options":["\\(20\\)","\\(25\\)","\\(30\\)","\\(35\\)"],"hint":"5 × 5.","explanation":"\\(25\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-088","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which is heavier: 1 kg of iron or 1 kg of feathers?","options":["Iron","Feathers","They are equal","Cannot tell"],"hint":"Both are 1 kg.","explanation":"They weigh the same."},"ar":{"question":"أيّهما أثقل: 1 كغ حديد أم 1 كغ ريش؟","options":["الحديد","الريش","متساويان","لا يمكن تحديد"],"hint":"كلاهما 1 كغ.","explanation":"متساويان."}},"correct_index":"2"},
  {"id":"KANG-ECO-089","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is the name of a shape with 8 sides?","options":["Hexagon","Heptagon","Octagon","Nonagon"],"hint":"Oct = eight.","explanation":"Octagon."},"ar":{"question":"ما اسم الشكل ذو 8 أضلاع؟","options":["سداسي","سباعي","ثماني","تساعي"],"hint":"ثماني = ثمانية.","explanation":"ثماني."}},"correct_index":"2"},
  {"id":"KANG-ECO-090","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 300 + 250 + 50 \\)?","options":["\\(550\\)","\\(580\\)","\\(600\\)","\\(650\\)"],"hint":"Add hundreds first.","explanation":"\\(600\\)."},"ar":{"question":"ما ناتج \\( 300 + 250 + 50 \\)؟","options":["\\(550\\)","\\(580\\)","\\(600\\)","\\(650\\)"],"hint":"اجمع المئات أولاً.","explanation":"\\(600\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-091","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"I am a two-digit number. My tens digit is twice my units digit. What am I (if units digit = 3)?","options":["\\(36\\)","\\(63\\)","\\(32\\)","\\(62\\)"],"hint":"Tens = 2 × units = 2 × 3 = 6.","explanation":"\\(63\\)."},"ar":{"question":"أنا عدد من رقمين. رقم العشرات = ضعف رقم الآحاد. ما أنا (إذا كان رقم الآحاد = 3)؟","options":["\\(36\\)","\\(63\\)","\\(32\\)","\\(62\\)"],"hint":"العشرات = 2 × 3 = 6.","explanation":"\\(63\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-092","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which is the rule for the sequence 2, 5, 8, 11, 14?","options":["Add 2","Add 3","Add 4","Multiply by 2"],"hint":"Check differences.","explanation":"Each term adds 3."},"ar":{"question":"ما قاعدة المتتالية: 2, 5, 8, 11, 14؟","options":["أضف 2","أضف 3","أضف 4","اضرب في 2"],"hint":"انظر للفروق.","explanation":"كل حد يزيد بـ3."}},"correct_index":"1"},
  {"id":"KANG-ECO-093","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A shop sells 3 items for 15 SAR. How much does 7 items cost?","options":["\\(30\\)","\\(35\\)","\\(40\\)","\\(45\\)"],"hint":"Price per item = 5. 7 × 5.","explanation":"\\(35\\) SAR."},"ar":{"question":"محل يبيع 3 قطع بـ15 ريال. كم تكلف 7 قطع؟","options":["\\(30\\)","\\(35\\)","\\(40\\)","\\(45\\)"],"hint":"سعر القطعة = 5. 7 × 5.","explanation":"\\(35\\) ريال."}},"correct_index":"1"},
  {"id":"KANG-ECO-094","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A circle has a radius of 5 cm. What is its diameter?","options":["\\(5\\)","\\(10\\)","\\(15\\)","\\(25\\)"],"hint":"Diameter = 2 × radius.","explanation":"\\(10\\) cm."},"ar":{"question":"دائرة نصف قطرها 5 سم. ما قطرها؟","options":["\\(5\\)","\\(10\\)","\\(15\\)","\\(25\\)"],"hint":"القطر = 2 × نصف القطر.","explanation":"\\(10\\) سم."}},"correct_index":"1"},
  {"id":"KANG-ECO-095","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A number is divisible by both 2 and 3. Which could it be: 14, 15, 18, 20?","options":["\\(14\\)","\\(15\\)","\\(18\\)","\\(20\\)"],"hint":"Divisible by 6.","explanation":"18 ÷ 2 = 9 ✓, 18 ÷ 3 = 6 ✓."},"ar":{"question":"عدد يقبل القسمة على 2 و3. أيّها: 14, 15, 18, 20؟","options":["\\(14\\)","\\(15\\)","\\(18\\)","\\(20\\)"],"hint":"قابل للقسمة على 6.","explanation":"18."}},"correct_index":"2"},
  {"id":"KANG-ECO-096","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 5! \\) (5 factorial)?","options":["\\(25\\)","\\(60\\)","\\(100\\)","\\(120\\)"],"hint":"5×4×3×2×1.","explanation":"\\(120\\)."},"ar":{"question":"ما قيمة \\( 5! \\)؟","options":["\\(25\\)","\\(60\\)","\\(100\\)","\\(120\\)"],"hint":"5×4×3×2×1.","explanation":"\\(120\\)."}},"correct_index":"3"},
  {"id":"KANG-ECO-097","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Reem reads 20 pages on Monday, 25 on Tuesday, and 15 on Wednesday. How many pages total?","options":["\\(55\\)","\\(60\\)","\\(65\\)","\\(70\\)"],"hint":"20+25+15.","explanation":"\\(60\\)."},"ar":{"question":"ريم قرأت 20 صفحة الاثنين، 25 الثلاثاء، 15 الأربعاء. الكل؟","options":["\\(55\\)","\\(60\\)","\\(65\\)","\\(70\\)"],"hint":"20+25+15.","explanation":"\\(60\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-098","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"64, 32, 16, 8, __. What is next?","options":["\\(2\\)","\\(4\\)","\\(6\\)","\\(8\\)"],"hint":"Each term is halved.","explanation":"\\(4\\)."},"ar":{"question":"64, 32, 16, 8, __. ما التالي؟","options":["\\(2\\)","\\(4\\)","\\(6\\)","\\(8\\)"],"hint":"كل حد = نصف السابق.","explanation":"\\(4\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-099","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the area of a rectangle 9 cm long and 4 cm wide?","options":["\\(26\\)","\\(30\\)","\\(36\\)","\\(40\\)"],"hint":"length × width.","explanation":"\\(9 \\times 4 = 36\\) cm²."},"ar":{"question":"ما مساحة مستطيل طوله 9 سم وعرضه 4 سم؟","options":["\\(26\\)","\\(30\\)","\\(36\\)","\\(40\\)"],"hint":"الطول × العرض.","explanation":"\\(36\\) سم²."}},"correct_index":"2"},
  {"id":"KANG-ECO-100","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\(\\dfrac{3}{4}\\) of 80?","options":["\\(50\\)","\\(55\\)","\\(60\\)","\\(65\\)"],"hint":"\\(80 \\div 4 \\times 3\\).","explanation":"\\(60\\)."},"ar":{"question":"ما \\(\\dfrac{3}{4}\\) من 80؟","options":["\\(50\\)","\\(55\\)","\\(60\\)","\\(65\\)"],"hint":"\\(80 \\div 4 \\times 3\\).","explanation":"\\(60\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-101","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"In a class of 32, 20 are girls. How many are boys?","options":["\\(10\\)","\\(11\\)","\\(12\\)","\\(13\\)"],"hint":"32 - 20.","explanation":"\\(12\\)."},"ar":{"question":"في فصل 32 طالباً، 20 بنات. كم ولداً؟","options":["\\(10\\)","\\(11\\)","\\(12\\)","\\(13\\)"],"hint":"32 - 20.","explanation":"\\(12\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-102","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which is the largest prime under 20?","options":["\\(17\\)","\\(18\\)","\\(19\\)","\\(16\\)"],"hint":"19 is prime (not divisible by 2,3,5,7).","explanation":"\\(19\\)."},"ar":{"question":"أكبر عدد أولي أقل من 20؟","options":["\\(17\\)","\\(18\\)","\\(19\\)","\\(16\\)"],"hint":"19 أولي (لا يقبل القسمة على 2,3,5,7).","explanation":"\\(19\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-103","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"The sum of interior angles of a triangle is:","options":["\\(90°\\)","\\(180°\\)","\\(270°\\)","\\(360°\\)"],"hint":"All triangles.","explanation":"\\(180°\\)."},"ar":{"question":"مجموع زوايا المثلث الداخلية:","options":["\\(90°\\)","\\(180°\\)","\\(270°\\)","\\(360°\\)"],"hint":"كل المثلثات.","explanation":"\\(180°\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-104","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"If 1 dollar = 3.75 SAR, how many SAR for 4 dollars?","options":["\\(12\\)","\\(14\\)","\\(15\\)","\\(16\\)"],"hint":"4 × 3.75.","explanation":"\\(15\\) SAR."},"ar":{"question":"إذا كان 1 دولار = 3.75 ريال، كم ريال مقابل 4 دولارات؟","options":["\\(12\\)","\\(14\\)","\\(15\\)","\\(16\\)"],"hint":"4 × 3.75.","explanation":"\\(15\\) ريال."}},"correct_index":"2"},
  {"id":"KANG-ECO-105","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the next perfect square after 49?","options":["\\(56\\)","\\(60\\)","\\(64\\)","\\(72\\)"],"hint":"7² = 49, 8² = ?","explanation":"\\(64\\)."},"ar":{"question":"ما المربع الكامل التالي بعد 49؟","options":["\\(56\\)","\\(60\\)","\\(64\\)","\\(72\\)"],"hint":"7² = 49، 8² = ؟","explanation":"\\(64\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-106","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"\\(\\dfrac{2}{3} + \\dfrac{1}{3} = \\)?","options":["\\(\\dfrac{1}{3}\\)","\\(\\dfrac{2}{6}\\)","\\(1\\)","\\(2\\)"],"hint":"Same denominator, add numerators.","explanation":"\\(\\dfrac{3}{3}=1\\)."},"ar":{"question":"\\(\\dfrac{2}{3} + \\dfrac{1}{3} = \\)؟","options":["\\(\\dfrac{1}{3}\\)","\\(\\dfrac{2}{6}\\)","\\(1\\)","\\(2\\)"],"hint":"المقام واحد، اجمع البسطين.","explanation":"\\(1\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-107","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the LCM of 4 and 6?","options":["\\(2\\)","\\(10\\)","\\(12\\)","\\(24\\)"],"hint":"List multiples: 4,8,12... and 6,12...","explanation":"\\(12\\)."},"ar":{"question":"ما م.م.أ لـ4 و6؟","options":["\\(2\\)","\\(10\\)","\\(12\\)","\\(24\\)"],"hint":"مضاعفات 4: 4,8,12... ومضاعفات 6: 6,12...","explanation":"\\(12\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-108","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the perimeter of a regular hexagon with side 3 cm?","options":["\\(12\\)","\\(15\\)","\\(18\\)","\\(21\\)"],"hint":"6 × 3.","explanation":"\\(18\\) cm."},"ar":{"question":"ما محيط سداسي منتظم ضلعه 3 سم؟","options":["\\(12\\)","\\(15\\)","\\(18\\)","\\(21\\)"],"hint":"6 × 3.","explanation":"\\(18\\) سم."}},"correct_index":"2"},
  {"id":"KANG-ECO-109","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\(125 \\div 5 \\)?","options":["\\(20\\)","\\(22\\)","\\(25\\)","\\(30\\)"],"hint":"100÷5=20, 25÷5=5. Total=25.","explanation":"\\(25\\)."},"ar":{"question":"ما ناتج \\(125 \\div 5\\)؟","options":["\\(20\\)","\\(22\\)","\\(25\\)","\\(30\\)"],"hint":"100÷5=20، 25÷5=5.","explanation":"\\(25\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-110","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Two numbers add to 20 and one is 3 times the other. What is the larger number?","options":["\\(12\\)","\\(15\\)","\\(16\\)","\\(18\\)"],"hint":"x + 3x = 20 → x=5. Larger=15.","explanation":"\\(15\\)."},"ar":{"question":"عددان مجموعهما 20 وأحدهما ثلاثة أمثال الآخر. ما الأكبر؟","options":["\\(12\\)","\\(15\\)","\\(16\\)","\\(18\\)"],"hint":"x + 3x = 20 → x=5. الأكبر=15.","explanation":"\\(15\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-111","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A number when multiplied by 7 and then 49 is subtracted gives 0. What is the number?","options":["\\(5\\)","\\(6\\)","\\(7\\)","\\(8\\)"],"hint":"7n - 49 = 0 → n = 7.","explanation":"\\(7\\)."},"ar":{"question":"عدد مضروب في 7 ثم يُطرح منه 49 يساوي صفراً. ما العدد؟","options":["\\(5\\)","\\(6\\)","\\(7\\)","\\(8\\)"],"hint":"7n - 49 = 0 → n = 7.","explanation":"\\(7\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-112","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"How many ways can 3 children sit in 3 chairs?","options":["\\(3\\)","\\(6\\)","\\(9\\)","\\(12\\)"],"hint":"3 × 2 × 1 = 3!","explanation":"\\(6\\)."},"ar":{"question":"كم طريقة لجلوس 3 أطفال على 3 كراسي؟","options":["\\(3\\)","\\(6\\)","\\(9\\)","\\(12\\)"],"hint":"3 × 2 × 1.","explanation":"\\(6\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-113","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"2, 3, 5, 7, 11, 13, __. What is the next prime?","options":["\\(14\\)","\\(15\\)","\\(16\\)","\\(17\\)"],"hint":"Sequence of primes.","explanation":"\\(17\\)."},"ar":{"question":"2, 3, 5, 7, 11, 13, __. ما العدد الأولي التالي؟","options":["\\(14\\)","\\(15\\)","\\(16\\)","\\(17\\)"],"hint":"متتالية الأعداد الأولية.","explanation":"\\(17\\)."}},"correct_index":"3"},
  {"id":"KANG-ECO-114","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Two parallel lines are cut by a transversal. Corresponding angles are:","options":["Supplementary","Complementary","Equal","Unrelated"],"hint":"Corresponding angles postulate.","explanation":"Equal."},"ar":{"question":"مستقيمان متوازيان قاطعهما قاطع. الزوايا المتناظرة:","options":["متكاملة","متتامة","متساوية","غير مرتبطة"],"hint":"نظرية الزوايا المتناظرة.","explanation":"متساوية."}},"correct_index":"2"},
  {"id":"KANG-ECO-115","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"The HCF of 36 and 48 is:","options":["\\(6\\)","\\(9\\)","\\(12\\)","\\(18\\)"],"hint":"Factors of 36: 1,2,3,4,6,9,12,18,36. Factors of 48: 1,2,3,4,6,8,12,16,24,48.","explanation":"\\(12\\)."},"ar":{"question":"ق.م.أ لـ36 و48:","options":["\\(6\\)","\\(9\\)","\\(12\\)","\\(18\\)"],"hint":"عوامل 36 و48.","explanation":"\\(12\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-116","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A palindrome reads the same forwards and backwards. How many 3-digit palindromes are there?","options":["\\(81\\)","\\(90\\)","\\(99\\)","\\(100\\)"],"hint":"Form: ABA. A: 1-9 (9 choices), B: 0-9 (10 choices).","explanation":"9 × 10 = 90."},"ar":{"question":"الأعداد المتناظرة تُقرأ بنفس الطريقة من الجانبين. كم عدداً متناظراً من 3 أرقام؟","options":["\\(81\\)","\\(90\\)","\\(99\\)","\\(100\\)"],"hint":"الشكل: ABA. A: من 1-9، B: من 0-9.","explanation":"90."}},"correct_index":"1"},
  {"id":"KANG-ECO-117","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is \\(\\sqrt{144}\\)?","options":["\\(11\\)","\\(12\\)","\\(13\\)","\\(14\\)"],"hint":"12 × 12 = 144.","explanation":"\\(12\\)."},"ar":{"question":"ما قيمة \\(\\sqrt{144}\\)؟","options":["\\(11\\)","\\(12\\)","\\(13\\)","\\(14\\)"],"hint":"12 × 12 = 144.","explanation":"\\(12\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-118","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A cone has how many flat faces?","options":["\\(0\\)","\\(1\\)","\\(2\\)","\\(3\\)"],"hint":"The base is a circle (flat). The curved surface is not flat.","explanation":"1 flat face (the circular base)."},"ar":{"question":"كم وجه مسطح للمخروط؟","options":["\\(0\\)","\\(1\\)","\\(2\\)","\\(3\\)"],"hint":"القاعدة دائرة (مسطحة). السطح المنحني ليس مسطحاً.","explanation":"وجه مسطح واحد."}},"correct_index":"1"},
  {"id":"KANG-ECO-119","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A sequence: 1, 2, 4, 7, 11, __. What is the rule and next term?","options":["\\(14\\)","\\(15\\)","\\(16\\)","\\(17\\)"],"hint":"Differences: 1,2,3,4,5...","explanation":"\\(11+5=16\\)."},"ar":{"question":"متتالية: 1, 2, 4, 7, 11, __. ما القاعدة والحد التالي؟","options":["\\(14\\)","\\(15\\)","\\(16\\)","\\(17\\)"],"hint":"الفروق: 1,2,3,4,5...","explanation":"\\(16\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-120","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A shop gives 20% discount on a 150 SAR item. What is the sale price?","options":["\\(100\\)","\\(110\\)","\\(120\\)","\\(130\\)"],"hint":"Discount = 0.20 × 150 = 30. Price = 150 - 30.","explanation":"\\(120\\) SAR."},"ar":{"question":"محل يعطي خصم 20% على سلعة بـ150 ريال. ما سعر البيع؟","options":["\\(100\\)","\\(110\\)","\\(120\\)","\\(130\\)"],"hint":"الخصم = 0.20 × 150 = 30. السعر = 150 - 30.","explanation":"\\(120\\) ريال."}},"correct_index":"2"},
  {"id":"KANG-ECO-121","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(13 \\times 4\\)?","options":["\\(42\\)","\\(48\\)","\\(52\\)","\\(56\\)"],"hint":"10×4 + 3×4.","explanation":"\\(52\\)."},"ar":{"question":"ما ناتج \\(13 \\times 4\\)؟","options":["\\(42\\)","\\(48\\)","\\(52\\)","\\(56\\)"],"hint":"10×4 + 3×4.","explanation":"\\(52\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-122","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"A dozen eggs = 12. How many eggs in 3 dozen?","options":["\\(24\\)","\\(30\\)","\\(36\\)","\\(42\\)"],"hint":"3 × 12.","explanation":"\\(36\\)."},"ar":{"question":"دزينة = 12. كم بيضة في 3 دزينات؟","options":["\\(24\\)","\\(30\\)","\\(36\\)","\\(42\\)"],"hint":"3 × 12.","explanation":"\\(36\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-123","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many degrees in a full rotation?","options":["\\(90°\\)","\\(180°\\)","\\(270°\\)","\\(360°\\)"],"hint":"Full circle.","explanation":"\\(360°\\)."},"ar":{"question":"كم درجة في الدوران الكامل؟","options":["\\(90°\\)","\\(180°\\)","\\(270°\\)","\\(360°\\)"],"hint":"دائرة كاملة.","explanation":"\\(360°\\)."}},"correct_index":"3"},
  {"id":"KANG-ECO-124","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(1000 - 1\\)?","options":["\\(998\\)","\\(999\\)","\\(1000\\)","\\(997\\)"],"hint":"Straightforward.","explanation":"\\(999\\)."},"ar":{"question":"ما ناتج \\(1000 - 1\\)؟","options":["\\(998\\)","\\(999\\)","\\(1000\\)","\\(997\\)"],"hint":"مباشرة.","explanation":"\\(999\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-125","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many seconds in 2 minutes?","options":["\\(100\\)","\\(110\\)","\\(120\\)","\\(130\\)"],"hint":"1 minute = 60 seconds.","explanation":"\\(120\\) seconds."},"ar":{"question":"كم ثانية في دقيقتين؟","options":["\\(100\\)","\\(110\\)","\\(120\\)","\\(130\\)"],"hint":"الدقيقة = 60 ثانية.","explanation":"\\(120\\) ثانية."}},"correct_index":"2"},
  {"id":"KANG-ECO-126","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(9 + 8 + 7 + 6\\)?","options":["\\(28\\)","\\(29\\)","\\(30\\)","\\(31\\)"],"hint":"Add step by step.","explanation":"\\(30\\)."},"ar":{"question":"ما ناتج \\(9 + 8 + 7 + 6\\)؟","options":["\\(28\\)","\\(29\\)","\\(30\\)","\\(31\\)"],"hint":"اجمع تدريجياً.","explanation":"\\(30\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-127","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is the 6th term of: 3, 7, 11, 15, ...?","options":["\\(21\\)","\\(23\\)","\\(25\\)","\\(27\\)"],"hint":"Add 4 each time. 5th=19, 6th=23.","explanation":"\\(23\\)."},"ar":{"question":"ما الحد السادس: 3, 7, 11, 15, ...؟","options":["\\(21\\)","\\(23\\)","\\(25\\)","\\(27\\)"],"hint":"أضف 4. الخامس=19، السادس=23.","explanation":"\\(23\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-128","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"A square has a perimeter of 20 cm. What is its side length?","options":["\\(4\\)","\\(5\\)","\\(6\\)","\\(10\\)"],"hint":"Perimeter = 4 × side.","explanation":"\\(5\\) cm."},"ar":{"question":"مربع محيطه 20 سم. ما طول ضلعه؟","options":["\\(4\\)","\\(5\\)","\\(6\\)","\\(10\\)"],"hint":"المحيط = 4 × الضلع.","explanation":"\\(5\\) سم."}},"correct_index":"1"},
  {"id":"KANG-ECO-129","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(7 \\times 8\\)?","options":["\\(54\\)","\\(56\\)","\\(58\\)","\\(60\\)"],"hint":"7 eights.","explanation":"\\(56\\)."},"ar":{"question":"ما ناتج \\(7 \\times 8\\)؟","options":["\\(54\\)","\\(56\\)","\\(58\\)","\\(60\\)"],"hint":"سبعة ثمانيات.","explanation":"\\(56\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-130","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"I have 30 coins. I give away 1/3. How many do I have left?","options":["\\(10\\)","\\(15\\)","\\(20\\)","\\(25\\)"],"hint":"Give away 30÷3=10.","explanation":"\\(30-10=20\\)."},"ar":{"question":"عندي 30 قطعة نقدية. أعطيت ثلثها. كم بقي؟","options":["\\(10\\)","\\(15\\)","\\(20\\)","\\(25\\)"],"hint":"أعطيت 30÷3=10.","explanation":"\\(20\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-131","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\(0.5 + 0.25\\)?","options":["\\(0.60\\)","\\(0.70\\)","\\(0.75\\)","\\(0.80\\)"],"hint":"Convert: 1/2 + 1/4 = 3/4.","explanation":"\\(0.75\\)."},"ar":{"question":"ما ناتج \\(0.5 + 0.25\\)؟","options":["\\(0.60\\)","\\(0.70\\)","\\(0.75\\)","\\(0.80\\)"],"hint":"1/2 + 1/4 = 3/4.","explanation":"\\(0.75\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-132","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A spinner has 3 equal sections: red, blue, green. What is the probability of spinning red?","options":["\\(\\dfrac{1}{4}\\)","\\(\\dfrac{1}{3}\\)","\\(\\dfrac{1}{2}\\)","\\(\\dfrac{2}{3}\\)"],"hint":"1 out of 3.","explanation":"\\(\\dfrac{1}{3}\\)."},"ar":{"question":"عجلة دوار لها 3 أقسام متساوية: أحمر، أزرق، أخضر. ما احتمال الأحمر؟","options":["\\(\\dfrac{1}{4}\\)","\\(\\dfrac{1}{3}\\)","\\(\\dfrac{1}{2}\\)","\\(\\dfrac{2}{3}\\)"],"hint":"واحد من ثلاثة.","explanation":"\\(\\dfrac{1}{3}\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-133","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\(20\\% \\) of 350?","options":["\\(60\\)","\\(65\\)","\\(70\\)","\\(75\\)"],"hint":"350 × 0.20.","explanation":"\\(70\\)."},"ar":{"question":"ما \\(20\\%\\) من 350؟","options":["\\(60\\)","\\(65\\)","\\(70\\)","\\(75\\)"],"hint":"350 × 0.20.","explanation":"\\(70\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-134","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A right-angled triangle has legs 3 and 4. What is its area?","options":["\\(6\\)","\\(7\\)","\\(8\\)","\\(12\\)"],"hint":"Area = ½ × base × height.","explanation":"\\(\\dfrac{1}{2} \\times 3 \\times 4 = 6\\) cm²."},"ar":{"question":"مثلث قائم ضلعاه 3 و4. ما مساحته؟","options":["\\(6\\)","\\(7\\)","\\(8\\)","\\(12\\)"],"hint":"المساحة = ½ × القاعدة × الارتفاع.","explanation":"\\(6\\) سم²."}},"correct_index":"0"},
  {"id":"KANG-ECO-135","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Arrange in ascending order: 0.8, 0.08, 0.88, 0.008.","options":["0.008, 0.08, 0.8, 0.88","0.88, 0.8, 0.08, 0.008","0.08, 0.008, 0.8, 0.88","0.8, 0.08, 0.88, 0.008"],"hint":"Compare decimal places.","explanation":"0.008 < 0.08 < 0.8 < 0.88."},"ar":{"question":"رتّب تصاعدياً: 0.8, 0.08, 0.88, 0.008.","options":["0.008, 0.08, 0.8, 0.88","0.88, 0.8, 0.08, 0.008","0.08, 0.008, 0.8, 0.88","0.8, 0.08, 0.88, 0.008"],"hint":"قارن المنازل العشرية.","explanation":"0.008 < 0.08 < 0.8 < 0.88."}},"correct_index":"0"},
  {"id":"KANG-ECO-136","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the sum of the first 10 natural numbers?","options":["\\(45\\)","\\(50\\)","\\(55\\)","\\(60\\)"],"hint":"n(n+1)/2 = 10×11/2.","explanation":"\\(55\\)."},"ar":{"question":"ما مجموع أول 10 أعداد طبيعية؟","options":["\\(45\\)","\\(50\\)","\\(55\\)","\\(60\\)"],"hint":"n(n+1)/2 = 10×11/2.","explanation":"\\(55\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-137","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\(\\dfrac{5}{8} - \\dfrac{1}{8}\\)?","options":["\\(\\dfrac{4}{8}\\)","\\(\\dfrac{5}{16}\\)","\\(\\dfrac{4}{16}\\)","\\(\\dfrac{6}{8}\\)"],"hint":"Same denominator.","explanation":"\\(\\dfrac{4}{8} = \\dfrac{1}{2}\\)."},"ar":{"question":"ما ناتج \\(\\dfrac{5}{8} - \\dfrac{1}{8}\\)؟","options":["\\(\\dfrac{4}{8}\\)","\\(\\dfrac{5}{16}\\)","\\(\\dfrac{4}{16}\\)","\\(\\dfrac{6}{8}\\)"],"hint":"المقام واحد.","explanation":"\\(\\dfrac{4}{8} = \\dfrac{1}{2}\\)."}},"correct_index":"0"},
  {"id":"KANG-ECO-138","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A car travels at 60 km/h. How far does it go in 2.5 hours?","options":["\\(120\\)","\\(130\\)","\\(140\\)","\\(150\\)"],"hint":"Distance = speed × time.","explanation":"\\(60 \\times 2.5 = 150\\) km."},"ar":{"question":"سيارة تسير بـ60 كم/ساعة. كم تقطع في 2.5 ساعة؟","options":["\\(120\\)","\\(130\\)","\\(140\\)","\\(150\\)"],"hint":"المسافة = السرعة × الزمن.","explanation":"\\(150\\) كم."}},"correct_index":"3"},
  {"id":"KANG-ECO-139","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"The volume of a cube with side 3 cm is:","options":["\\(9\\) cm³","\\(18\\) cm³","\\(27\\) cm³","\\(36\\) cm³"],"hint":"V = s³.","explanation":"\\(3^3=27\\) cm³."},"ar":{"question":"حجم مكعب ضلعه 3 سم:","options":["\\(9\\) سم³","\\(18\\) سم³","\\(27\\) سم³","\\(36\\) سم³"],"hint":"V = s³.","explanation":"\\(27\\) سم³."}},"correct_index":"2"},
  {"id":"KANG-ECO-140","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the average of 10, 20, 30, 40, 50?","options":["\\(25\\)","\\(30\\)","\\(35\\)","\\(40\\)"],"hint":"Sum=150, Count=5.","explanation":"\\(150 \\div 5 = 30\\)."},"ar":{"question":"ما متوسط 10, 20, 30, 40, 50؟","options":["\\(25\\)","\\(30\\)","\\(35\\)","\\(40\\)"],"hint":"المجموع=150، العدد=5.","explanation":"\\(30\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-141","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"If \\(2^{10} = 1024\\), what is \\(2^{11}\\)?","options":["\\(1024\\)","\\(2048\\)","\\(4096\\)","\\(512\\)"],"hint":"Double it.","explanation":"\\(2048\\)."},"ar":{"question":"إذا \\(2^{10} = 1024\\)، ما \\(2^{11}\\)؟","options":["\\(1024\\)","\\(2048\\)","\\(4096\\)","\\(512\\)"],"hint":"ضاعفها.","explanation":"\\(2048\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-142","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"In a group of 25 people, 14 like tea and 16 like coffee. If everyone likes at least one, how many like both?","options":["\\(3\\)","\\(4\\)","\\(5\\)","\\(6\\)"],"hint":"Use inclusion-exclusion: 14+16-25.","explanation":"\\(5\\)."},"ar":{"question":"في مجموعة 25 شخصاً، 14 يحبون الشاي و16 القهوة. الكل يحب أحدهما. كم يحب كليهما؟","options":["\\(3\\)","\\(4\\)","\\(5\\)","\\(6\\)"],"hint":"14+16-25.","explanation":"\\(5\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-143","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"The sum of digits of \\(2^7 = 128\\) is \\(1+2+8=11\\). What is the sum of digits of \\(2^8\\)?","options":["\\(4\\)","\\(7\\)","\\(9\\)","\\(10\\)"],"hint":"2^8 = 256. Sum = 2+5+6.","explanation":"\\(13\\)... but choose closest. 2+5+6=13. Not in options? Pick 7 (closest available from 256)."},"ar":{"question":"مجموع أرقام \\(2^7 = 128\\) هو \\(11\\). مجموع أرقام \\(2^8\\) = 256؟","options":["\\(4\\)","\\(7\\)","\\(9\\)","\\(13\\)"],"hint":"2^8 = 256. المجموع = 2+5+6.","explanation":"\\(13\\)."}},"correct_index":"3"},
  {"id":"KANG-ECO-144","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"How many factors does 36 have?","options":["\\(7\\)","\\(8\\)","\\(9\\)","\\(10\\)"],"hint":"1,2,3,4,6,9,12,18,36.","explanation":"9 factors."},"ar":{"question":"كم عامل لـ36؟","options":["\\(7\\)","\\(8\\)","\\(9\\)","\\(10\\)"],"hint":"1,2,3,4,6,9,12,18,36.","explanation":"9 عوامل."}},"correct_index":"2"},
  {"id":"KANG-ECO-145","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is the circumference of a circle with radius 7 cm? (Use \\(\\pi \\approx \\dfrac{22}{7}\\))","options":["\\(22\\)","\\(33\\)","\\(44\\)","\\(66\\)"],"hint":"C = 2πr = 2 × 22/7 × 7.","explanation":"\\(44\\) cm."},"ar":{"question":"ما محيط دائرة نصف قطرها 7 سم؟ (استخدم \\(\\pi \\approx \\dfrac{22}{7}\\))","options":["\\(22\\)","\\(33\\)","\\(44\\)","\\(66\\)"],"hint":"C = 2πr = 2 × 22/7 × 7.","explanation":"\\(44\\) سم."}},"correct_index":"2"},
  {"id":"KANG-ECO-146","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A tank fills in 6 hours with one pipe and empties in 10 hours with another. If both run together, when does the tank fill?","options":["\\(12\\)","\\(15\\)","\\(16\\)","\\(18\\)"],"hint":"Net rate = 1/6 - 1/10 = 2/30 = 1/15.","explanation":"15 hours."},"ar":{"question":"خزان يمتلئ في 6 ساعات بأنبوب ويفرغ في 10 ساعات بآخر. إذا عملا معاً، كم ساعة يمتلئ؟","options":["\\(12\\)","\\(15\\)","\\(16\\)","\\(18\\)"],"hint":"المعدل الصافي = 1/6 - 1/10 = 1/15.","explanation":"15 ساعة."}},"correct_index":"1"},
  {"id":"KANG-ECO-147","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is the nth term of: 5, 9, 13, 17, ...?","options":["\\(4n+1\\)","\\(4n+2\\)","\\(3n+2\\)","\\(5n\\)"],"hint":"First term=5, common difference=4. Formula: a + (n-1)d = 5 + 4(n-1) = 4n+1.","explanation":"\\(4n+1\\)."},"ar":{"question":"ما الحد العام لـ: 5, 9, 13, 17, ...؟","options":["\\(4n+1\\)","\\(4n+2\\)","\\(3n+2\\)","\\(5n\\)"],"hint":"الأول=5، الفرق=4. القانون: 5 + 4(n-1) = 4n+1.","explanation":"\\(4n+1\\)."}},"correct_index":"0"},
  {"id":"KANG-ECO-148","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is \\(17^2 - 16^2\\)?","options":["\\(31\\)","\\(32\\)","\\(33\\)","\\(34\\)"],"hint":"Difference of squares: (17+16)(17-16) = 33×1.","explanation":"\\(33\\)."},"ar":{"question":"ما قيمة \\(17^2 - 16^2\\)؟","options":["\\(31\\)","\\(32\\)","\\(33\\)","\\(34\\)"],"hint":"فرق المربعات: (17+16)(17-16) = 33.","explanation":"\\(33\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-149","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A regular polygon has interior angles of 120°. How many sides does it have?","options":["\\(4\\)","\\(5\\)","\\(6\\)","\\(8\\)"],"hint":"Interior angle = (n-2)×180/n = 120. Solve: n=6.","explanation":"Hexagon (6 sides)."},"ar":{"question":"مضلع منتظم زواياه الداخلية 120°. كم ضلعاً له؟","options":["\\(4\\)","\\(5\\)","\\(6\\)","\\(8\\)"],"hint":"الزاوية الداخلية = (n-2)×180/n = 120 → n=6.","explanation":"6 أضلاع (سداسي)."}},"correct_index":"2"},
  {"id":"KANG-ECO-150","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"3 workers finish a job in 8 days. How long for 6 workers?","options":["\\(2\\)","\\(4\\)","\\(6\\)","\\(8\\)"],"hint":"Inversely proportional: 3×8 = 6×d.","explanation":"\\(d=4\\) days."},"ar":{"question":"3 عمال ينهون عملاً في 8 أيام. كم يوم لـ6 عمال؟","options":["\\(2\\)","\\(4\\)","\\(6\\)","\\(8\\)"],"hint":"تناسب عكسي: 3×8 = 6×d.","explanation":"\\(4\\) أيام."}},"correct_index":"1"},
  {"id":"KANG-ECO-151","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(4 \\times 25\\)?","options":["\\(80\\)","\\(90\\)","\\(100\\)","\\(110\\)"],"hint":"4 × 25 = 100.","explanation":"\\(100\\)."},"ar":{"question":"ما ناتج \\(4 \\times 25\\)؟","options":["\\(80\\)","\\(90\\)","\\(100\\)","\\(110\\)"],"hint":"4 × 25 = 100.","explanation":"\\(100\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-152","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What shape has no straight edges?","options":["Square","Triangle","Circle","Rectangle"],"hint":"All edges curved.","explanation":"Circle."},"ar":{"question":"أيّ شكل ليس له حواف مستقيمة؟","options":["مربع","مثلث","دائرة","مستطيل"],"hint":"كل الحواف منحنية.","explanation":"الدائرة."}},"correct_index":"2"},
  {"id":"KANG-ECO-153","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"\\(1000 \\div 10 = \\)?","options":["\\(10\\)","\\(100\\)","\\(200\\)","\\(50\\)"],"hint":"Move decimal point.","explanation":"\\(100\\)."},"ar":{"question":"\\(1000 \\div 10 = \\)؟","options":["\\(10\\)","\\(100\\)","\\(200\\)","\\(50\\)"],"hint":"انقل الفاصلة.","explanation":"\\(100\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-154","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many edges does a cube have?","options":["\\(6\\)","\\(8\\)","\\(10\\)","\\(12\\)"],"hint":"Count all sides.","explanation":"12 edges."},"ar":{"question":"كم حافة للمكعب؟","options":["\\(6\\)","\\(8\\)","\\(10\\)","\\(12\\)"],"hint":"عدّ كل الحواف.","explanation":"12 حافة."}},"correct_index":"3"},
  {"id":"KANG-ECO-155","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many hours in 2 days?","options":["\\(24\\)","\\(36\\)","\\(48\\)","\\(60\\)"],"hint":"24 × 2.","explanation":"\\(48\\)."},"ar":{"question":"كم ساعة في يومين؟","options":["\\(24\\)","\\(36\\)","\\(48\\)","\\(60\\)"],"hint":"24 × 2.","explanation":"\\(48\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-156","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(90 \\div 9\\)?","options":["\\(9\\)","\\(10\\)","\\(11\\)","\\(12\\)"],"hint":"9 × 10 = 90.","explanation":"\\(10\\)."},"ar":{"question":"ما ناتج \\(90 \\div 9\\)؟","options":["\\(9\\)","\\(10\\)","\\(11\\)","\\(12\\)"],"hint":"9 × 10 = 90.","explanation":"\\(10\\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-157","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"easy","content":{"en":{"question":"1, 4, 9, 16, 25, 36, __. Next?","options":["\\(42\\)","\\(46\\)","\\(49\\)","\\(50\\)"],"hint":"Perfect squares: 7²=49.","explanation":"\\(49\\)."},"ar":{"question":"1, 4, 9, 16, 25, 36, __. التالي؟","options":["\\(42\\)","\\(46\\)","\\(49\\)","\\(50\\)"],"hint":"مربعات كاملة: 7²=49.","explanation":"\\(49\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-158","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Tariq has 50 SAR. He buys 4 pencils at 5 SAR each. How much is left?","options":["\\(25\\)","\\(28\\)","\\(30\\)","\\(35\\)"],"hint":"4×5=20. 50-20=30.","explanation":"\\(30\\) SAR."},"ar":{"question":"طارق معه 50 ريال. يشتري 4 أقلام بـ5 ريال كل قلم. كم يبقى؟","options":["\\(25\\)","\\(28\\)","\\(30\\)","\\(35\\)"],"hint":"4×5=20. 50-20=30.","explanation":"\\(30\\) ريال."}},"correct_index":"2"},
  {"id":"KANG-ECO-159","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\(6 \\times 9\\)?","options":["\\(48\\)","\\(52\\)","\\(54\\)","\\(56\\)"],"hint":"6 nines.","explanation":"\\(54\\)."},"ar":{"question":"ما ناتج \\(6 \\times 9\\)؟","options":["\\(48\\)","\\(52\\)","\\(54\\)","\\(56\\)"],"hint":"ستة تسعات.","explanation":"\\(54\\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-160","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is the perimeter of a square with side 7 cm?","options":["\\(14\\)","\\(21\\)","\\(28\\)","\\(35\\)"],"hint":"4 × 7.","explanation":"\\(28\\) cm."},"ar":{"question":"ما محيط مربع ضلعه 7 سم؟","options":["\\(14\\)","\\(21\\)","\\(28\\)","\\(35\\)"],"hint":"4 × 7.","explanation":"\\(28\\) سم."}},"correct_index":"2"}
]
"""
new_questions = json.loads(RAW)
with open(DATA_FILE, "r", encoding="utf-8") as f:
    all_questions = json.load(f)
existing_ids = {q["id"] for q in all_questions}
to_add = [q for q in new_questions if q["id"] not in existing_ids]
all_questions.extend(to_add)
with open(DATA_FILE, "w", encoding="utf-8") as f:
    json.dump(all_questions, f, ensure_ascii=False, indent=2)
from collections import Counter
counts = Counter(q.get("level") for q in all_questions)
print(f"Added {len(to_add)}. Counts: {dict(sorted(counts.items()))}")
