#!/usr/bin/env python3
"""Kangaroo Ecolier (Grades 3-4) - Batch 1: questions 1-80"""
import json
DATA_FILE = "data/kangaroo.json"
RAW = r"""
[
  {"id":"KANG-ECO-001","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 24 + 37 \\)?","options":["\\( 51 \\)","\\( 61 \\)","\\( 71 \\)","\\( 60 \\)"],"hint":"Add tens, then ones.","explanation":"\\( 24+37=61 \\)."},"ar":{"question":"ما ناتج \\( 24 + 37 \\)؟","options":["\\( 51 \\)","\\( 61 \\)","\\( 71 \\)","\\( 60 \\)"],"hint":"اجمع العشرات ثم الآحاد.","explanation":"\\( 61 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-002","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 100 - 43 \\)?","options":["\\( 57 \\)","\\( 63 \\)","\\( 47 \\)","\\( 67 \\)"],"hint":"Borrow from hundreds.","explanation":"\\( 100-43=57 \\)."},"ar":{"question":"ما ناتج \\( 100 - 43 \\)؟","options":["\\( 57 \\)","\\( 63 \\)","\\( 47 \\)","\\( 67 \\)"],"hint":"احترس من الاستعارة.","explanation":"\\( 57 \\)."}},"correct_index":"0"},
  {"id":"KANG-ECO-003","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What comes next? 2, 4, 6, 8, __","options":["\\( 9 \\)","\\( 10 \\)","\\( 12 \\)","\\( 11 \\)"],"hint":"Add 2 each time.","explanation":"\\( 8+2=10 \\)."},"ar":{"question":"ما التالي؟ 2, 4, 6, 8, __","options":["\\( 9 \\)","\\( 10 \\)","\\( 12 \\)","\\( 11 \\)"],"hint":"أضف 2 في كل مرة.","explanation":"\\( 10 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-004","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many sides does a triangle have?","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 5 \\)"],"hint":"Think of the word 'tri'.","explanation":"A triangle has 3 sides."},"ar":{"question":"كم ضلعاً للمثلث؟","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 5 \\)"],"hint":"فكر في كلمة مثلث.","explanation":"للمثلث 3 أضلاع."}},"correct_index":"1"},
  {"id":"KANG-ECO-005","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Sara has 5 apples. She gives 2 to Tom. How many does Sara have left?","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 7 \\)"],"hint":"Subtract what she gave away.","explanation":"\\( 5-2=3 \\)."},"ar":{"question":"سارة لديها 5 تفاحات. أعطت 2 لتوم. كم بقي معها؟","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 7 \\)"],"hint":"اطرح ما أعطته.","explanation":"\\( 5-2=3 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-006","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 6 \\times 7 \\)?","options":["\\( 36 \\)","\\( 42 \\)","\\( 48 \\)","\\( 56 \\)"],"hint":"6 sevens.","explanation":"\\( 6 \\times 7 = 42 \\)."},"ar":{"question":"ما ناتج \\( 6 \\times 7 \\)؟","options":["\\( 36 \\)","\\( 42 \\)","\\( 48 \\)","\\( 56 \\)"],"hint":"ستة سبعات.","explanation":"\\( 42 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-007","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What comes next? 1, 3, 5, 7, __","options":["\\( 8 \\)","\\( 9 \\)","\\( 10 \\)","\\( 11 \\)"],"hint":"Odd numbers sequence.","explanation":"\\( 7+2=9 \\)."},"ar":{"question":"ما التالي؟ 1, 3, 5, 7, __","options":["\\( 8 \\)","\\( 9 \\)","\\( 10 \\)","\\( 11 \\)"],"hint":"متتالية الأعداد الفردية.","explanation":"\\( 9 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-008","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many corners does a square have?","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 6 \\)"],"hint":"Count the angles.","explanation":"A square has 4 corners."},"ar":{"question":"كم زاوية للمربع؟","options":["\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 6 \\)"],"hint":"عدّ الزوايا.","explanation":"للمربع 4 زوايا."}},"correct_index":"2"},
  {"id":"KANG-ECO-009","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which number is the largest? 15, 9, 21, 17","options":["\\( 15 \\)","\\( 9 \\)","\\( 21 \\)","\\( 17 \\)"],"hint":"Compare all values.","explanation":"\\( 21 \\) is the largest."},"ar":{"question":"أيّ عدد أكبر؟ 15, 9, 21, 17","options":["\\( 15 \\)","\\( 9 \\)","\\( 21 \\)","\\( 17 \\)"],"hint":"قارن كل القيم.","explanation":"\\( 21 \\) هو الأكبر."}},"correct_index":"2"},
  {"id":"KANG-ECO-010","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"\\( 56 \\div 8 = \\) ?","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"8 times what equals 56?","explanation":"\\( 8 \\times 7 = 56 \\)."},"ar":{"question":"\\( 56 \\div 8 = \\) ؟","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"ماذا يساوي 8 × ؟ = 56","explanation":"\\( 7 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-011","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"A bag has 3 red and 4 blue marbles. How many marbles in total?","options":["\\( 5 \\)","\\( 6 \\)","\\( 7 \\)","\\( 8 \\)"],"hint":"Add both colours.","explanation":"\\( 3+4=7 \\)."},"ar":{"question":"كيس فيه 3 كرات حمراء و4 زرقاء. كم مجموعها؟","options":["\\( 5 \\)","\\( 6 \\)","\\( 7 \\)","\\( 8 \\)"],"hint":"اجمع اللونين.","explanation":"\\( 7 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-012","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is half of 18?","options":["\\( 6 \\)","\\( 8 \\)","\\( 9 \\)","\\( 10 \\)"],"hint":"Divide by 2.","explanation":"\\( 18 \\div 2 = 9 \\)."},"ar":{"question":"ما نصف 18؟","options":["\\( 6 \\)","\\( 8 \\)","\\( 9 \\)","\\( 10 \\)"],"hint":"اقسم على 2.","explanation":"\\( 9 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-013","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"The pattern is: ⬛⬜⬛⬜⬛__. What comes next?","options":["⬛","⬜","⬛⬜","⬜⬛"],"hint":"Alternating pattern.","explanation":"The pattern alternates ⬛⬜. After ⬛ comes ⬜."},"ar":{"question":"النمط: ⬛⬜⬛⬜⬛__. ما التالي؟","options":["⬛","⬜","⬛⬜","⬜⬛"],"hint":"نمط متناوب.","explanation":"بعد ⬛ يأتي ⬜."}},"correct_index":"1"},
  {"id":"KANG-ECO-014","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many faces does a cube have?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 8 \\)"],"hint":"Think of a dice.","explanation":"A cube has 6 faces."},"ar":{"question":"كم وجه للمكعب؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 8 \\)"],"hint":"فكر في حجر النرد.","explanation":"للمكعب 6 وجوه."}},"correct_index":"2"},
  {"id":"KANG-ECO-015","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 9 \\times 9 \\)?","options":["\\( 72 \\)","\\( 81 \\)","\\( 90 \\)","\\( 99 \\)"],"hint":"9 nines.","explanation":"\\( 9 \\times 9=81 \\)."},"ar":{"question":"ما ناتج \\( 9 \\times 9 \\)؟","options":["\\( 72 \\)","\\( 81 \\)","\\( 90 \\)","\\( 99 \\)"],"hint":"تسعة تسعات.","explanation":"\\( 81 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-016","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Ali is taller than Ben. Ben is taller than Carl. Who is shortest?","options":["Ali","Ben","Carl","They are equal"],"hint":"Compare in order.","explanation":"Carl is shortest."},"ar":{"question":"علي أطول من بن. بن أطول من كارل. من الأقصر؟","options":["علي","بن","كارل","متساوون"],"hint":"قارن بالترتيب.","explanation":"كارل هو الأقصر."}},"correct_index":"2"},
  {"id":"KANG-ECO-017","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 50 + 50 \\)?","options":["\\( 55 \\)","\\( 100 \\)","\\( 105 \\)","\\( 110 \\)"],"hint":"Two fifties.","explanation":"\\( 50+50=100 \\)."},"ar":{"question":"ما ناتج \\( 50 + 50 \\)؟","options":["\\( 55 \\)","\\( 100 \\)","\\( 105 \\)","\\( 110 \\)"],"hint":"خمسون زائد خمسون.","explanation":"\\( 100 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-018","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"A rectangle has 2 sides of length 5 and 2 sides of length 3. What is its perimeter?","options":["\\( 13 \\)","\\( 15 \\)","\\( 16 \\)","\\( 8 \\)"],"hint":"Add all 4 sides.","explanation":"\\( 5+3+5+3=16 \\)."},"ar":{"question":"مستطيل ضلعاه الطويلان 5 والقصيران 3. ما محيطه؟","options":["\\( 13 \\)","\\( 15 \\)","\\( 16 \\)","\\( 8 \\)"],"hint":"اجمع الأضلاع الأربعة.","explanation":"\\( 16 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-019","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"5, 10, 15, 20, __. What is next?","options":["\\( 22 \\)","\\( 24 \\)","\\( 25 \\)","\\( 30 \\)"],"hint":"Multiples of 5.","explanation":"\\( 20+5=25 \\)."},"ar":{"question":"5, 10, 15, 20, __. ما التالي؟","options":["\\( 22 \\)","\\( 24 \\)","\\( 25 \\)","\\( 30 \\)"],"hint":"مضاعفات 5.","explanation":"\\( 25 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-020","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"There are 12 eggs in a box. 4 are broken. How many are not broken?","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"Subtract broken ones.","explanation":"\\( 12-4=8 \\)."},"ar":{"question":"صندوق فيه 12 بيضة. 4 منها مكسورة. كم غير مكسور؟","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"اطرح المكسورة.","explanation":"\\( 8 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-021","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 3 \\times 4 + 2 \\)?","options":["\\( 12 \\)","\\( 14 \\)","\\( 16 \\)","\\( 18 \\)"],"hint":"Multiply first, then add.","explanation":"\\( 12+2=14 \\)."},"ar":{"question":"ما ناتج \\( 3 \\times 4 + 2 \\)؟","options":["\\( 12 \\)","\\( 14 \\)","\\( 16 \\)","\\( 18 \\)"],"hint":"اضرب أولاً ثم اجمع.","explanation":"\\( 14 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-022","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"I have 3 coins. Each coin is 5 riyals. How much do I have in total?","options":["\\( 8 \\)","\\( 10 \\)","\\( 15 \\)","\\( 20 \\)"],"hint":"3 × 5.","explanation":"\\( 3 \\times 5=15 \\)."},"ar":{"question":"لدي 3 قطع نقدية. كل قطعة 5 ريالات. كم مجموعها؟","options":["\\( 8 \\)","\\( 10 \\)","\\( 15 \\)","\\( 20 \\)"],"hint":"3 × 5.","explanation":"\\( 15 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-023","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which shape has no corners?","options":["Triangle","Square","Circle","Rectangle"],"hint":"Curved shape.","explanation":"A circle has no corners."},"ar":{"question":"أيّ شكل ليس له زوايا؟","options":["مثلث","مربع","دائرة","مستطيل"],"hint":"شكل منحنٍ.","explanation":"الدائرة ليس لها زوايا."}},"correct_index":"2"},
  {"id":"KANG-ECO-024","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 72 \\div 9 \\)?","options":["\\( 7 \\)","\\( 8 \\)","\\( 9 \\)","\\( 6 \\)"],"hint":"9 × ? = 72.","explanation":"\\( 9 \\times 8=72 \\)."},"ar":{"question":"ما ناتج \\( 72 \\div 9 \\)؟","options":["\\( 7 \\)","\\( 8 \\)","\\( 9 \\)","\\( 6 \\)"],"hint":"9 × ؟ = 72.","explanation":"\\( 8 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-025","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"If today is Wednesday, what day was it 3 days ago?","options":["Monday","Sunday","Tuesday","Saturday"],"hint":"Count back 3 days.","explanation":"Wed → Tue → Mon → Sun. 3 days ago was Sunday."},"ar":{"question":"إذا كان اليوم الأربعاء، ما كان اليوم قبل 3 أيام؟","options":["الاثنين","الأحد","الثلاثاء","السبت"],"hint":"عدّ للخلف 3 أيام.","explanation":"الأربعاء → الثلاثاء → الاثنين → الأحد."}},"correct_index":"1"},
  {"id":"KANG-ECO-026","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 25 + 25 + 25 + 25 \\)?","options":["\\( 75 \\)","\\( 80 \\)","\\( 100 \\)","\\( 125 \\)"],"hint":"4 × 25.","explanation":"\\( 4 \\times 25=100 \\)."},"ar":{"question":"ما ناتج \\( 25 + 25 + 25 + 25 \\)؟","options":["\\( 75 \\)","\\( 80 \\)","\\( 100 \\)","\\( 125 \\)"],"hint":"4 × 25.","explanation":"\\( 100 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-027","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"1, 4, 9, 16, __. What comes next?","options":["\\( 20 \\)","\\( 25 \\)","\\( 24 \\)","\\( 36 \\)"],"hint":"Perfect squares: 1², 2², 3², 4², 5²...","explanation":"\\( 5^2=25 \\)."},"ar":{"question":"1, 4, 9, 16, __. ما التالي؟","options":["\\( 20 \\)","\\( 25 \\)","\\( 24 \\)","\\( 36 \\)"],"hint":"مربعات كاملة.","explanation":"\\( 5^2=25 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-028","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A square has a side of 4 cm. What is its area?","options":["\\( 8 \\) cm²","\\( 12 \\) cm²","\\( 16 \\) cm²","\\( 20 \\) cm²"],"hint":"Area = side × side.","explanation":"\\( 4 \\times 4=16 \\) cm²."},"ar":{"question":"مربع ضلعه 4 سم. ما مساحته؟","options":["\\( 8 \\) سم²","\\( 12 \\) سم²","\\( 16 \\) سم²","\\( 20 \\) سم²"],"hint":"المساحة = الضلع × الضلع.","explanation":"\\( 16 \\) سم²."}},"correct_index":"2"},
  {"id":"KANG-ECO-029","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"There are 5 children. Each gets 3 sweets. How many sweets in total?","options":["\\( 8 \\)","\\( 12 \\)","\\( 15 \\)","\\( 18 \\)"],"hint":"Multiply.","explanation":"\\( 5 \\times 3=15 \\)."},"ar":{"question":"5 أطفال. كل طفل يحصل على 3 حلويات. كم المجموع؟","options":["\\( 8 \\)","\\( 12 \\)","\\( 15 \\)","\\( 18 \\)"],"hint":"اضرب.","explanation":"\\( 15 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-030","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which is the smallest fraction? \\( \\dfrac{1}{2}, \\dfrac{1}{3}, \\dfrac{1}{4}, \\dfrac{1}{5} \\)","options":["\\( \\dfrac{1}{2} \\)","\\( \\dfrac{1}{3} \\)","\\( \\dfrac{1}{4} \\)","\\( \\dfrac{1}{5} \\)"],"hint":"Larger denominator = smaller fraction.","explanation":"\\( \\dfrac{1}{5} \\) is the smallest."},"ar":{"question":"أيّ الكسور أصغر؟ \\( \\dfrac{1}{2}, \\dfrac{1}{3}, \\dfrac{1}{4}, \\dfrac{1}{5} \\)","options":["\\( \\dfrac{1}{2} \\)","\\( \\dfrac{1}{3} \\)","\\( \\dfrac{1}{4} \\)","\\( \\dfrac{1}{5} \\)"],"hint":"المقام الأكبر يعني كسراً أصغر.","explanation":"\\( \\dfrac{1}{5} \\)."}},"correct_index":"3"},
  {"id":"KANG-ECO-031","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"2, 6, 18, 54, __. What comes next?","options":["\\( 108 \\)","\\( 162 \\)","\\( 108 \\)","\\( 216 \\)"],"hint":"Multiply by 3 each time.","explanation":"\\( 54 \\times 3=162 \\)."},"ar":{"question":"2, 6, 18, 54, __. ما التالي؟","options":["\\( 108 \\)","\\( 162 \\)","\\( 108 \\)","\\( 216 \\)"],"hint":"اضرب في 3 في كل مرة.","explanation":"\\( 162 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-032","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A train leaves at 9:00 AM and arrives at 11:30 AM. How long is the journey?","options":["\\( 1.5 \\) hours","\\( 2 \\) hours","\\( 2.5 \\) hours","\\( 3 \\) hours"],"hint":"Count from 9:00 to 11:30.","explanation":"From 9:00 to 11:30 = 2 hours 30 minutes = 2.5 hours."},"ar":{"question":"قطار يغادر 9:00 ص ويصل 11:30 ص. كم مدة الرحلة؟","options":["\\( 1.5 \\) ساعة","\\( 2 \\) ساعة","\\( 2.5 \\) ساعة","\\( 3 \\) ساعة"],"hint":"احسب من 9:00 إلى 11:30.","explanation":"2.5 ساعة."}},"correct_index":"2"},
  {"id":"KANG-ECO-033","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 12 \\times 5 \\)?","options":["\\( 50 \\)","\\( 55 \\)","\\( 60 \\)","\\( 65 \\)"],"hint":"10×5 + 2×5.","explanation":"\\( 60 \\)."},"ar":{"question":"ما ناتج \\( 12 \\times 5 \\)؟","options":["\\( 50 \\)","\\( 55 \\)","\\( 60 \\)","\\( 65 \\)"],"hint":"10×5 + 2×5.","explanation":"\\( 60 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-034","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"How many right angles does a rectangle have?","options":["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)"],"hint":"Each corner of a rectangle is 90°.","explanation":"4 right angles."},"ar":{"question":"كم زاوية قائمة للمستطيل؟","options":["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)"],"hint":"كل زاوية في المستطيل 90°.","explanation":"4 زوايا قائمة."}},"correct_index":"3"},
  {"id":"KANG-ECO-035","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which comes first in alphabetical order? CAT, ANT, DOG, BEE","options":["CAT","ANT","DOG","BEE"],"hint":"Look at the first letter: A, B, C, D.","explanation":"ANT starts with A, which comes first."},"ar":{"question":"أيّ كلمة تأتي أولاً أبجدياً؟ CAT, ANT, DOG, BEE","options":["CAT","ANT","DOG","BEE"],"hint":"انظر للحرف الأول.","explanation":"ANT تبدأ بـA."}},"correct_index":"1"},
  {"id":"KANG-ECO-036","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 200 - 75 \\)?","options":["\\( 115 \\)","\\( 120 \\)","\\( 125 \\)","\\( 130 \\)"],"hint":"200 - 75: borrow carefully.","explanation":"\\( 125 \\)."},"ar":{"question":"ما ناتج \\( 200 - 75 \\)؟","options":["\\( 115 \\)","\\( 120 \\)","\\( 125 \\)","\\( 130 \\)"],"hint":"احترس من الاستعارة.","explanation":"\\( 125 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-037","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"I think of a number, multiply by 2, then add 4. I get 14. What was my number?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"Work backwards: 14-4=10, 10÷2=5.","explanation":"Number = 5."},"ar":{"question":"فكرت في عدد، ضربته في 2، أضفت 4. النتيجة 14. ما العدد؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"اعمل للخلف: 14-4=10, 10÷2=5.","explanation":"العدد = 5."}},"correct_index":"1"},
  {"id":"KANG-ECO-038","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"100, 90, 80, 70, __. What comes next?","options":["\\( 50 \\)","\\( 55 \\)","\\( 60 \\)","\\( 65 \\)"],"hint":"Subtract 10 each time.","explanation":"\\( 70-10=60 \\)."},"ar":{"question":"100, 90, 80, 70, __. ما التالي؟","options":["\\( 50 \\)","\\( 55 \\)","\\( 60 \\)","\\( 65 \\)"],"hint":"اطرح 10 في كل مرة.","explanation":"\\( 60 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-039","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A triangle has one angle of 90° and another of 45°. What is the third angle?","options":["\\( 30° \\)","\\( 45° \\)","\\( 60° \\)","\\( 90° \\)"],"hint":"Angles in a triangle sum to 180°.","explanation":"\\( 180-90-45=45° \\)."},"ar":{"question":"مثلث زاوية منه 90° وأخرى 45°. ما الزاوية الثالثة؟","options":["\\( 30° \\)","\\( 45° \\)","\\( 60° \\)","\\( 90° \\)"],"hint":"مجموع زوايا المثلث 180°.","explanation":"\\( 45° \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-040","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is the sum of the first 5 odd numbers?","options":["\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 15 \\)"],"hint":"1+3+5+7+9.","explanation":"\\( 1+3+5+7+9=25 \\)."},"ar":{"question":"ما مجموع أول 5 أعداد فردية؟","options":["\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 15 \\)"],"hint":"1+3+5+7+9.","explanation":"\\( 25 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-041","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"5 cats catch 5 mice in 5 minutes. How many cats are needed to catch 25 mice in 25 minutes?","options":["\\( 1 \\)","\\( 5 \\)","\\( 10 \\)","\\( 25 \\)"],"hint":"Each cat catches 1 mouse per 5 minutes; in 25 min = 5 mice. So 5 cats catch 25 mice.","explanation":"5 cats."},"ar":{"question":"5 قطط تمسك 5 فئران في 5 دقائق. كم قطة تلزم لمسك 25 فأراً في 25 دقيقة؟","options":["\\( 1 \\)","\\( 5 \\)","\\( 10 \\)","\\( 25 \\)"],"hint":"كل قطة تمسك فأراً كل 5 دقائق. في 25 دقيقة كل قطة تمسك 5 فئران.","explanation":"5 قطط."}},"correct_index":"1"},
  {"id":"KANG-ECO-042","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is \\( 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 \\)?","options":["\\( 45 \\)","\\( 50 \\)","\\( 55 \\)","\\( 60 \\)"],"hint":"Pair numbers: (1+10), (2+9)...","explanation":"5 pairs × 11 = 55."},"ar":{"question":"ما مجموع \\( 1 + 2 + ... + 10 \\)؟","options":["\\( 45 \\)","\\( 50 \\)","\\( 55 \\)","\\( 60 \\)"],"hint":"رتّبها أزواجاً: (1+10), (2+9)...","explanation":"5 أزواج × 11 = 55."}},"correct_index":"2"},
  {"id":"KANG-ECO-043","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"1, 1, 2, 3, 5, 8, __. What is next?","options":["\\( 10 \\)","\\( 11 \\)","\\( 13 \\)","\\( 15 \\)"],"hint":"Fibonacci: add previous two.","explanation":"\\( 5+8=13 \\)."},"ar":{"question":"1, 1, 2, 3, 5, 8, __. ما التالي؟","options":["\\( 10 \\)","\\( 11 \\)","\\( 13 \\)","\\( 15 \\)"],"hint":"فيبوناتشي: اجمع السابقين.","explanation":"\\( 13 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-044","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A clock shows 3:15. What is the angle between the hour and minute hands?","options":["\\( 0° \\)","\\( 7.5° \\)","\\( 15° \\)","\\( 22.5° \\)"],"hint":"At 3:15, minute hand is at 90°. Hour hand moves 0.5° per minute. At 3:00 it's at 90°, after 15 min it's at 97.5°.","explanation":"Minute at 90°, hour at 97.5°. Difference = 7.5°."},"ar":{"question":"ساعة تُظهر 3:15. ما الزاوية بين عقربي الساعات والدقائق؟","options":["\\( 0° \\)","\\( 7.5° \\)","\\( 15° \\)","\\( 22.5° \\)"],"hint":"عقرب الدقائق عند 90°. عقرب الساعات يتحرك 0.5° كل دقيقة.","explanation":"الفرق = 7.5°."}},"correct_index":"1"},
  {"id":"KANG-ECO-045","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"How many small squares are in a 4×4 grid (counting all sizes)?","options":["\\( 16 \\)","\\( 20 \\)","\\( 30 \\)","\\( 36 \\)"],"hint":"Count 1×1, 2×2, 3×3, 4×4 squares.","explanation":"16+9+4+1=30."},"ar":{"question":"كم مربعاً في شبكة 4×4 (بجميع الأحجام)؟","options":["\\( 16 \\)","\\( 20 \\)","\\( 30 \\)","\\( 36 \\)"],"hint":"عدّ مربعات 1×1, 2×2, 3×3, 4×4.","explanation":"16+9+4+1=30."}},"correct_index":"2"},
  {"id":"KANG-ECO-046","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is the remainder when 100 is divided by 7?","options":["\\( 1 \\)","\\( 2 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"\\( 7 \\times 14 = 98 \\).","explanation":"\\( 100 = 7 \\times 14 + 2 \\). Remainder = 2."},"ar":{"question":"ما الباقي من قسمة 100 على 7؟","options":["\\( 1 \\)","\\( 2 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"\\( 7 \\times 14 = 98 \\).","explanation":"الباقي = 2."}},"correct_index":"1"},
  {"id":"KANG-ECO-047","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"In a row of 10 students, Hana is 4th from the left. What position is she from the right?","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 4 \\)"],"hint":"Position from right = total + 1 - position from left.","explanation":"\\( 10+1-4=7 \\)."},"ar":{"question":"في صف 10 طلاب، هناء في المركز الرابع من اليسار. ما مركزها من اليمين؟","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 4 \\)"],"hint":"المركز من اليمين = المجموع + 1 - المركز من اليسار.","explanation":"\\( 10+1-4=7 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-048","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"3, 6, 11, 18, 27, __. What comes next?","options":["\\( 36 \\)","\\( 38 \\)","\\( 40 \\)","\\( 38 \\)"],"hint":"Differences: 3, 5, 7, 9, 11...","explanation":"\\( 27+11=38 \\)."},"ar":{"question":"3, 6, 11, 18, 27, __. ما التالي؟","options":["\\( 36 \\)","\\( 38 \\)","\\( 40 \\)","\\( 42 \\)"],"hint":"الفروق: 3, 5, 7, 9, 11...","explanation":"\\( 27+11=38 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-049","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"I have some stickers. I give away half, then get 5 more, and now have 13. How many did I start with?","options":["\\( 12 \\)","\\( 14 \\)","\\( 16 \\)","\\( 18 \\)"],"hint":"Work backwards: 13-5=8, 8×2=16.","explanation":"Started with 16."},"ar":{"question":"عندي ملصقات. أعطيت نصفها، ثم حصلت على 5، والآن عندي 13. كم كان عندي؟","options":["\\( 12 \\)","\\( 14 \\)","\\( 16 \\)","\\( 18 \\)"],"hint":"اعمل للخلف: 13-5=8, 8×2=16.","explanation":"بدأت بـ16."}},"correct_index":"2"},
  {"id":"KANG-ECO-050","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A rectangular field is 12 m long and 8 m wide. A path 1 m wide is built inside around it. What is the area of the path?","options":["\\( 36 \\) m²","\\( 40 \\) m²","\\( 44 \\) m²","\\( 96 \\) m²"],"hint":"Inner area = (12-2)(8-2)=60. Outer area = 96. Path = 96-60.","explanation":"\\( 96-60=36 \\) m²."},"ar":{"question":"حديقة مستطيلة 12م × 8م. مسار عرضه 1م يُبنى داخلها. ما مساحة المسار؟","options":["\\( 36 \\) م²","\\( 40 \\) م²","\\( 44 \\) م²","\\( 96 \\) م²"],"hint":"المساحة الداخلية = 10×6=60. الخارجية = 96.","explanation":"\\( 36 \\) م²."}},"correct_index":"0"},
  {"id":"KANG-ECO-051","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 7^2 \\)?","options":["\\( 14 \\)","\\( 42 \\)","\\( 49 \\)","\\( 56 \\)"],"hint":"7 × 7.","explanation":"\\( 49 \\)."},"ar":{"question":"ما قيمة \\( 7^2 \\)؟","options":["\\( 14 \\)","\\( 42 \\)","\\( 49 \\)","\\( 56 \\)"],"hint":"7 × 7.","explanation":"\\( 49 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-052","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"There are 4 red pens, 6 blue pens, and 5 green pens. How many pens total?","options":["\\( 13 \\)","\\( 14 \\)","\\( 15 \\)","\\( 16 \\)"],"hint":"Add all.","explanation":"\\( 4+6+5=15 \\)."},"ar":{"question":"4 أقلام حمراء، 6 زرقاء، 5 خضراء. الكل؟","options":["\\( 13 \\)","\\( 14 \\)","\\( 15 \\)","\\( 16 \\)"],"hint":"اجمع الكل.","explanation":"\\( 15 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-053","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Round 347 to the nearest hundred.","options":["\\( 300 \\)","\\( 350 \\)","\\( 400 \\)","\\( 340 \\)"],"hint":"Is 47 closer to 0 or 100?","explanation":"47 < 50, so round down to 300."},"ar":{"question":"قرّب 347 لأقرب مئة.","options":["\\( 300 \\)","\\( 350 \\)","\\( 400 \\)","\\( 340 \\)"],"hint":"هل 47 أقرب لـ0 أم 100؟","explanation":"47 < 50، نقرّب لـ300."}},"correct_index":"0"},
  {"id":"KANG-ECO-054","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"How many vertices does a pentagon have?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"Same as the number of sides.","explanation":"A pentagon has 5 vertices."},"ar":{"question":"كم رأس للخماسي؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"مثل عدد الأضلاع.","explanation":"5 رؤوس."}},"correct_index":"1"},
  {"id":"KANG-ECO-055","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A book has 120 pages. Laila reads 15 pages per day. How many days to finish?","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"120 ÷ 15.","explanation":"\\( 120 \\div 15=8 \\) days."},"ar":{"question":"كتاب 120 صفحة. ليلى تقرأ 15 صفحة يومياً. كم يوم للانتهاء؟","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"120 ÷ 15.","explanation":"\\( 8 \\) أيام."}},"correct_index":"2"},
  {"id":"KANG-ECO-056","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 3^3 \\)?","options":["\\( 6 \\)","\\( 9 \\)","\\( 18 \\)","\\( 27 \\)"],"hint":"3 × 3 × 3.","explanation":"\\( 27 \\)."},"ar":{"question":"ما قيمة \\( 3^3 \\)؟","options":["\\( 6 \\)","\\( 9 \\)","\\( 18 \\)","\\( 27 \\)"],"hint":"3 × 3 × 3.","explanation":"\\( 27 \\)."}},"correct_index":"3"},
  {"id":"KANG-ECO-057","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"medium","content":{"en":{"question":"A, B, A, B, A, __. What comes next?","options":["A","B","C","AB"],"hint":"Alternating A and B.","explanation":"B."},"ar":{"question":"أ، ب، أ، ب، أ، __. ما التالي؟","options":["أ","ب","ج","أب"],"hint":"تناوب بين أ وب.","explanation":"ب."}},"correct_index":"1"},
  {"id":"KANG-ECO-058","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"There are 30 students. 18 like football. How many do not like football?","options":["\\( 10 \\)","\\( 11 \\)","\\( 12 \\)","\\( 13 \\)"],"hint":"30 - 18.","explanation":"\\( 12 \\)."},"ar":{"question":"30 طالب. 18 يحبون كرة القدم. كم لا يحبها؟","options":["\\( 10 \\)","\\( 11 \\)","\\( 12 \\)","\\( 13 \\)"],"hint":"30 - 18.","explanation":"\\( 12 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-059","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( \\dfrac{1}{2} + \\dfrac{1}{4} \\)?","options":["\\( \\dfrac{2}{6} \\)","\\( \\dfrac{2}{4} \\)","\\( \\dfrac{3}{4} \\)","\\( \\dfrac{1}{4} \\)"],"hint":"Convert to quarters: 2/4 + 1/4.","explanation":"\\( \\dfrac{3}{4} \\)."},"ar":{"question":"ما ناتج \\( \\dfrac{1}{2} + \\dfrac{1}{4} \\)؟","options":["\\( \\dfrac{2}{6} \\)","\\( \\dfrac{2}{4} \\)","\\( \\dfrac{3}{4} \\)","\\( \\dfrac{1}{4} \\)"],"hint":"حوّل لأرباع: 2/4 + 1/4.","explanation":"\\( \\dfrac{3}{4} \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-060","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"medium","content":{"en":{"question":"Which of these is a 3D shape?","options":["Circle","Triangle","Sphere","Square"],"hint":"3D shapes have volume.","explanation":"A sphere is a 3D shape."},"ar":{"question":"أيّ هذه الأشكال ثلاثي الأبعاد؟","options":["دائرة","مثلث","كرة","مربع"],"hint":"الأشكال ثلاثية الأبعاد لها حجم.","explanation":"الكرة."}},"correct_index":"2"},
  {"id":"KANG-ECO-061","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"medium","content":{"en":{"question":"What is \\( 15\\% \\) of \\( 200 \\)?","options":["\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 35 \\)"],"hint":"\\( \\dfrac{15}{100} \\times 200 \\).","explanation":"\\( 30 \\)."},"ar":{"question":"ما \\( 15\\% \\) من \\( 200 \\)؟","options":["\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 35 \\)"],"hint":"\\( \\dfrac{15}{100} \\times 200 \\).","explanation":"\\( 30 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-062","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A snail climbs 3 m per day and slips 1 m per night. The well is 10 m deep. How many days to escape?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"Net gain: 2m/day. After 4 days = 8m. Day 5: climbs to 11m.","explanation":"5 days."},"ar":{"question":"حلزون يتسلق 3م نهاراً وينزل 1م ليلاً. البئر 10م. كم يوم للخروج؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"صافي التقدم: 2م/يوم. بعد 4 أيام = 8م. اليوم 5: يتسلق 11م.","explanation":"5 أيام."}},"correct_index":"1"},
  {"id":"KANG-ECO-063","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Find the missing number: 2, __, 8, 16, 32.","options":["\\( 3 \\)","\\( 4 \\)","\\( 6 \\)","\\( 5 \\)"],"hint":"Each is doubled.","explanation":"\\( 2 \\times 2=4 \\)."},"ar":{"question":"أوجد المفقود: 2, __, 8, 16, 32.","options":["\\( 3 \\)","\\( 4 \\)","\\( 6 \\)","\\( 5 \\)"],"hint":"كل عدد يُضاعَف.","explanation":"\\( 4 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-064","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"Four friends share a pizza equally. Each gets 3 slices. How many slices total?","options":["\\( 8 \\)","\\( 10 \\)","\\( 12 \\)","\\( 16 \\)"],"hint":"4 × 3.","explanation":"\\( 12 \\)."},"ar":{"question":"4 أصدقاء يقسمون بيتزا بالتساوي. كل واحد يحصل على 3 قطع. كم مجموع القطع؟","options":["\\( 8 \\)","\\( 10 \\)","\\( 12 \\)","\\( 16 \\)"],"hint":"4 × 3.","explanation":"\\( 12 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-065","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is \\( 999 + 999 \\)?","options":["\\( 1{,}899 \\)","\\( 1{,}998 \\)","\\( 2{,}000 \\)","\\( 1{,}900 \\)"],"hint":"\\( 1000+1000-2 \\).","explanation":"\\( 1{,}998 \\)."},"ar":{"question":"ما ناتج \\( 999 + 999 \\)؟","options":["\\( 1{,}899 \\)","\\( 1{,}998 \\)","\\( 2{,}000 \\)","\\( 1{,}900 \\)"],"hint":"\\( 1000+1000-2 \\).","explanation":"\\( 1{,}998 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-066","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A right triangle has legs 6 and 8 cm. What is the hypotenuse?","options":["\\( 10 \\)","\\( 12 \\)","\\( 14 \\)","\\( 9 \\)"],"hint":"Pythagorean triple: 6, 8, 10.","explanation":"\\( \\sqrt{36+64}=10 \\)."},"ar":{"question":"مثلث قائم ضلعاه 6 و8 سم. ما الوتر؟","options":["\\( 10 \\)","\\( 12 \\)","\\( 14 \\)","\\( 9 \\)"],"hint":"الثلاثية الفيثاغورية: 6, 8, 10.","explanation":"\\( 10 \\)."}},"correct_index":"0"},
  {"id":"KANG-ECO-067","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A farmer has both chickens and cows. He counts 20 heads and 56 legs. How many cows?","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"Chickens=c, cows=w. c+w=20, 2c+4w=56.","explanation":"2(20)+2w=56 → 2w=16 → w=8."},"ar":{"question":"مزارع لديه دجاج وبقر. عدّ 20 رأساً و56 قدماً. كم بقرة؟","options":["\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],"hint":"دجاج+بقر=20. 2×20+2×بقر=56.","explanation":"8 بقرات."}},"correct_index":"2"},
  {"id":"KANG-ECO-068","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"What is \\( 2 + 4 + 6 + 8 + \\ldots + 20 \\)?","options":["\\( 100 \\)","\\( 110 \\)","\\( 90 \\)","\\( 120 \\)"],"hint":"10 even numbers. Average = 11. Sum = 10 × 11.","explanation":"\\( 110 \\)."},"ar":{"question":"ما مجموع \\( 2 + 4 + 6 + \\ldots + 20 \\)؟","options":["\\( 100 \\)","\\( 110 \\)","\\( 90 \\)","\\( 120 \\)"],"hint":"10 أعداد زوجية. المتوسط = 11.","explanation":"\\( 110 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-069","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"hard","content":{"en":{"question":"How many triangles are in this figure (a large triangle divided into 4 equal smaller triangles)?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"Count 4 small + 1 large.","explanation":"5 triangles."},"ar":{"question":"كم مثلثاً في شكل (مثلث كبير مقسم لـ4 مثلثات متساوية)؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 7 \\)"],"hint":"4 صغيرة + 1 كبيرة.","explanation":"5 مثلثات."}},"correct_index":"1"},
  {"id":"KANG-ECO-070","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"hard","content":{"en":{"question":"A magic square has rows/columns/diagonals all sum to 15. One cell shows 5. The center of a 3×3 magic square is always:","options":["\\( 3 \\)","\\( 5 \\)","\\( 7 \\)","\\( 9 \\)"],"hint":"The center of a 3×3 magic square with sum 15 is always 5.","explanation":"Center = 5."},"ar":{"question":"مربع سحري مجموع صفوفه/أعمدته/أقطاره = 15. مركز المربع السحري 3×3 دائماً:","options":["\\( 3 \\)","\\( 5 \\)","\\( 7 \\)","\\( 9 \\)"],"hint":"المركز = المجموع ÷ 3.","explanation":"المركز = 5."}},"correct_index":"1"},
  {"id":"KANG-ECO-071","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 8 + 9 + 7 \\)?","options":["\\( 22 \\)","\\( 23 \\)","\\( 24 \\)","\\( 25 \\)"],"hint":"Add step by step.","explanation":"\\( 8+9=17, 17+7=24 \\)."},"ar":{"question":"ما ناتج \\( 8 + 9 + 7 \\)؟","options":["\\( 22 \\)","\\( 23 \\)","\\( 24 \\)","\\( 25 \\)"],"hint":"اجمع خطوةً بخطوة.","explanation":"\\( 24 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-072","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"A box has 4 rows and 3 columns of chocolate. How many chocolates?","options":["\\( 7 \\)","\\( 10 \\)","\\( 12 \\)","\\( 14 \\)"],"hint":"Rows × columns.","explanation":"\\( 4 \\times 3=12 \\)."},"ar":{"question":"صندوق شوكولاته: 4 صفوف و3 أعمدة. كم قطعة؟","options":["\\( 7 \\)","\\( 10 \\)","\\( 12 \\)","\\( 14 \\)"],"hint":"الصفوف × الأعمدة.","explanation":"\\( 12 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-073","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"How many sides does a hexagon have?","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 8 \\)"],"hint":"Hex = six.","explanation":"6 sides."},"ar":{"question":"كم ضلع للسداسي؟","options":["\\( 4 \\)","\\( 5 \\)","\\( 6 \\)","\\( 8 \\)"],"hint":"السداسي = ستة.","explanation":"6 أضلاع."}},"correct_index":"2"},
  {"id":"KANG-ECO-074","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 45 - 18 \\)?","options":["\\( 25 \\)","\\( 26 \\)","\\( 27 \\)","\\( 28 \\)"],"hint":"Borrow from the tens.","explanation":"\\( 27 \\)."},"ar":{"question":"ما ناتج \\( 45 - 18 \\)؟","options":["\\( 25 \\)","\\( 26 \\)","\\( 27 \\)","\\( 28 \\)"],"hint":"استعر من العشرات.","explanation":"\\( 27 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-075","track":"kangaroo","level":"Ecolier","topic":"Patterns","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is the 10th term of 3, 6, 9, 12, ...?","options":["\\( 27 \\)","\\( 30 \\)","\\( 33 \\)","\\( 36 \\)"],"hint":"Multiply position by 3.","explanation":"\\( 10 \\times 3=30 \\)."},"ar":{"question":"ما الحد العاشر في: 3, 6, 9, 12, ...؟","options":["\\( 27 \\)","\\( 30 \\)","\\( 33 \\)","\\( 36 \\)"],"hint":"اضرب الترتيب في 3.","explanation":"\\( 30 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-076","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Mom baked 24 cookies. She divided them equally among 6 children. How many each?","options":["\\( 3 \\)","\\( 4 \\)","\\( 5 \\)","\\( 6 \\)"],"hint":"24 ÷ 6.","explanation":"\\( 4 \\) each."},"ar":{"question":"أم خبزت 24 كعكة. قسّمتها على 6 أطفال بالتساوي. كم لكل واحد؟","options":["\\( 3 \\)","\\( 4 \\)","\\( 5 \\)","\\( 6 \\)"],"hint":"24 ÷ 6.","explanation":"\\( 4 \\)."}},"correct_index":"1"},
  {"id":"KANG-ECO-077","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"Which is even: 17, 23, 36, 41?","options":["\\( 17 \\)","\\( 23 \\)","\\( 36 \\)","\\( 41 \\)"],"hint":"Even numbers end in 0,2,4,6,8.","explanation":"36 ends in 6 → even."},"ar":{"question":"أيّ الأعداد زوجي: 17, 23, 36, 41؟","options":["\\( 17 \\)","\\( 23 \\)","\\( 36 \\)","\\( 41 \\)"],"hint":"الأعداد الزوجية تنتهي بـ0,2,4,6,8.","explanation":"36 ينتهي بـ6 → زوجي."}},"correct_index":"2"},
  {"id":"KANG-ECO-078","track":"kangaroo","level":"Ecolier","topic":"Geometry","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What shape is a door?","options":["Circle","Triangle","Rectangle","Hexagon"],"hint":"Four sides, two longer.","explanation":"A door is rectangular."},"ar":{"question":"ما شكل الباب؟","options":["دائرة","مثلث","مستطيل","سداسي"],"hint":"أربعة أضلاع، ضلعان أطول.","explanation":"الباب مستطيل."}},"correct_index":"2"},
  {"id":"KANG-ECO-079","track":"kangaroo","level":"Ecolier","topic":"Logic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"There are 7 days in a week. How many days in 3 weeks?","options":["\\( 14 \\)","\\( 18 \\)","\\( 21 \\)","\\( 24 \\)"],"hint":"3 × 7.","explanation":"\\( 21 \\) days."},"ar":{"question":"7 أيام في الأسبوع. كم يوم في 3 أسابيع؟","options":["\\( 14 \\)","\\( 18 \\)","\\( 21 \\)","\\( 24 \\)"],"hint":"3 × 7.","explanation":"\\( 21 \\)."}},"correct_index":"2"},
  {"id":"KANG-ECO-080","track":"kangaroo","level":"Ecolier","topic":"Arithmetic","type":"MCQ","difficulty":"easy","content":{"en":{"question":"What is \\( 4 + 4 + 4 + 4 \\)?","options":["\\( 12 \\)","\\( 14 \\)","\\( 16 \\)","\\( 20 \\)"],"hint":"4 × 4.","explanation":"\\( 16 \\)."},"ar":{"question":"ما ناتج \\( 4 + 4 + 4 + 4 \\)؟","options":["\\( 12 \\)","\\( 14 \\)","\\( 16 \\)","\\( 20 \\)"],"hint":"4 × 4.","explanation":"\\( 16 \\)."}},"correct_index":"2"}
]
"""
new_questions = json.loads(RAW)
with open(DATA_FILE, "r", encoding="utf-8") as f:
    all_questions = json.load(f)
existing_ids = {q["id"] for q in all_questions}
to_add = [q for q in new_questions if q["id"] not in existing_ids]
all_questions.extend(to_add)
with open(DATA_FILE, "w", encoding="utf-8") as f:
    json.dump(all_questions, f, ensure_ascii=False, indent=2)
from collections import Counter
counts = Counter(q.get("level") for q in all_questions)
print(f"Added {len(to_add)}. Counts: {dict(sorted(counts.items()))}")
